### ISSUE TITLE
How to keep user installed python package when k8s kernel pod recreated

### ISSUE THREAD

**Issue by wuminorb** [jupyter/enterprise_gateway#1004]
## Description
Hi, my team are trying  to use enterprise gateway on kubernetes to serve our data science team. Some of our user will install additional python package inside their kernel ( using conda or pip ), how do we keep those packages for our user when kernel be culled and recreated?

I know there is a possible solution that mount a PV to user's home directory inside kernel container's. And use `pip install --user` to let pip install the packages there. Is there a way for `conda` to do the same thing? And since people sometimes forget to add `--user` option,  is there any other solution that can just using `pip install` or `conda install`? 

Thanks in advance.

**Comment by kevin-bates** [comment]
Hi @wuminorb - good question.  I believe this is more of a container behavior question than anything else.  The one area where we may want to investigate is _manual kernel restarts_.  Today, I'm fairly certain that restarting a kernel will destroy the container (i.e., pod), thereby discarding any changes made within that container.  Culling _should_ do just that since it represents a complete termination.

As for how to proceed now, I believe your choices are:
1. Use mount points (and deal with `--user`). I'm not enough of a pip aficionado to know how you'd get conda commands to work from your kernel other than using the `!` operator (e.g., `!conda install...`)
2. Another approach would be to [extend the kernel images](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/docker.html#extending-existing-kernel-images) and use those new images.  New images can override the image configured in the kernelspec by setting the environment variable [`KERNEL_IMAGE`](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/config-options.html#per-kernel-environment-overrides) on the client-side prior to starting notebook.  Whatever image is specified by that env will then be used.  The downside to this is that users would need to use the same image and can't really change between kernels.

I hope you find this helpful - although I'm sure its not ideal.

**Comment by wuminorb** [comment]
Thank you @kevin-bates for answering this. Looking forward for the new features that coming for this area
