### ISSUE TITLE
Log files for kernel launch got rewritten after restart

### ISSUE THREAD

**Issue by faurik** [jupyter/enterprise_gateway#1013]
## Description
JEG saves log files for each remote kernel launch into separate files like this: `${EG_KERNEL_LOG_DIR}/kernel-{kernel_id}.log`. The problem is that when kernel got restarted for some reason, JEG tries to restart it automatically, and after restart new kernel has the same `kernel_id`, and rewrites all logs of previous kernel (before restart).

## Screenshots / Logs
Piece of JEG logs, where we can see restart at `04:38:50`:
```
Nov 23 04:32:47 HOSTNAME jupyter[2389]: [I 2021-11-23 04:32:47.710 EnterpriseGatewayApp] Kernel started: 37ab22f2-bab4-4314-b62c-1543633c806b, name: spark_python3_yarn_client
<...>
Nov 23 04:38:47 HOSTNAME jupyter[2389]: [I 2021-11-23 04:38:47.866 EnterpriseGatewayApp] Kernel interrupted: 37ab22f2-bab4-4314-b62c-1543633c806b
Nov 23 04:38:47 HOSTNAME jupyter[2389]: [I 211123 04:38:47 web:2243] 204 POST /api/kernels/37ab22f2-bab4-4314-b62c-1543633c806b/interrupt (IP) 1.68ms
Nov 23 04:38:48 HOSTNAME jupyter[2389]: [D 2021-11-23 04:38:48.235 EnterpriseGatewayApp] activity on 37ab22f2-bab4-4314-b62c-1543633c806b: error
Nov 23 04:38:48 HOSTNAME jupyter[2389]: [D 2021-11-23 04:38:48.238 EnterpriseGatewayApp] activity on 37ab22f2-bab4-4314-b62c-1543633c806b: status (idle)
Nov 23 04:38:50 HOSTNAME jupyter[2389]: [W 211123 04:38:50 handlers:601] kernel 37ab22f2-bab4-4314-b62c-1543633c806b restarted
<...>
Nov 23 04:38:53 HOSTNAME jupyter[2389]: [D 2021-11-23 04:38:53.526 EnterpriseGatewayApp] Refreshing kernel session for id: 37ab22f2-bab4-4314-b62c-1543633c806b
<...>
Nov 23 04:53:30 HOSTNAME jupyter[2389]: [I 2021-11-23 04:53:30.628 EnterpriseGatewayApp] Kernel shutdown: 37ab22f2-bab4-4314-b62c-1543633c806b
Nov 23 04:53:33 HOSTNAME jupyter[2389]: [I 211123 04:53:33 web:2243] 204 DELETE /api/kernels/37ab22f2-bab4-4314-b62c-1543633c806b (IP) 2914.12ms
```

And piece of kernel's log, where we can see it started at `04:38:53` with no logs of previous run.
```
[D 2021-11-23 04:38:53,515.515 launch_ipykernel] Using connection file '/tmp/kernel-37ab22f2-bab4-4314-b62c-1543633c806b_e0cn_k0_.json'.
[I 2021-11-23 04:38:53,516.516 launch_ipykernel] Signal socket bound to host: 0.0.0.0, port: 59258
```

## Environment

- Enterprise Gateway Version [2.4.0]
- Platform: [YARN]

**Comment by faurik** [comment]
I am not really sure, but I have a feeling that this issue caused by [this line](https://github.com/jupyter/enterprise_gateway/blob/9719e6f9641d42013839ea4311cdfd6147a98e5c/enterprise_gateway/services/processproxies/distributed.py#L69). Here log file is opened with `mode='w'`, and, probably, on restart of kernel the log file got truncated. I suggest to use `mode='a'` in order to append logs of each restart to the same file instead of removing previous logs.

**Comment by kevin-bates** [comment]
Hi @faurik - thank you for opening this issue - this is a good catch!

The line you point out is for when the IP of the target host happens to be local, but I agree that it should be addressed as well.  The remote _log file management_ occurs [here](https://github.com/jupyter/enterprise_gateway/blob/9719e6f9641d42013839ea4311cdfd6147a98e5c/enterprise_gateway/services/processproxies/distributed.py#L116) where the redirection syntax should use concatenation.  (Hmm, for the remote case, I see concatenation is already in use: `' >> {} 2>&1 & echo $!'.format(self.kernel_log)`, so that should be okay.   Can you confirm that the case you're dealing with is when the local host is in the list of hosts to round-robin across?)

Since UUIDs are rarely recycled and because I'm not sure we have knowledge that the launch request is for the purposes of a restart, I suggest that we update the `open()` to use append mode, even for the initial start sequence.  The downside to that is in the (extremely) rare case when a UUID has been recycled, and I suspect, even then, timestamps could be used to distinguish the conflicting requests.  That is, I don't think it's worth the effort to avoid.

Please confirm your scenario (that you're seeing this with local files only).  Would you like to contribute this change?

**Comment by faurik** [comment]
Hi @kevin-bates, thank you for very prompt reply!

I accidentally wrote about _remote_ kernels (really don't know how it happened 🤦 ), we do not use them. We use local kernels, and the issue was caused exactly by the highlighted line of code (with `mode='w'`). I have already tested it and can confirm that replacing `mode='w'` with `mode='a'` solves the issue.

I agree that UUID can be rarely recycled. Total amount of UUIDs is about 3.4 x 10^38, so I believe we should not face reuse of the same UUID.

Yes, I would like to contribute this small fix.
