### ISSUE TITLE
Document lightweight kubernetes sidecar architecture (if possible)

### ISSUE THREAD

**Issue by elibixby** [jupyter/enterprise_gateway#1016]
Hey all, I'm just diving into this project and trying to combine it with my JupyterHub deployment in Kubernetes.

I'm planning on trying out a sidecar architecture: Just deploy an enterprise gateway container along-side each user notebook container in the same pod. The notebook container can talk to the enterprise server over localhost.

As far as I can tell, the only benefits of a central server are: (1) Allows for ingress from outside the cluster, and (2) allows for an highly available place for image pre-pullers to check for new kernels.

(1) is not a use case I want to support, and I don't think I need (2) as image streaming in GKE makes pod startup very fast.

Any obvious pitfalls to this approach that I'm missing?

**Comment by kevin-bates** [comment]
Hi @elibixby - the design center around EG is that it be used as a single server for multiple notebook clients.  That said, many applications spin up an EG server on a per-user basis.  I think this could be accomplished by adjusting the EG deployment's namespace to match that of the Notebook pod's, but you'd also be incurring deployment cost on each notebook server launch and EG is quite heavy.

This use-case is precisely the use-case in which [_kernel provisioners_](https://jupyter-client.readthedocs.io/en/latest/provisioning.html) are meant to address.  With kernel provisioners, you'd install a ["Kubernetes Provisioner"](https://github.com/kevin-bates/remote_provisioners) directly in your notebook server image, along with the associated kernelspecs that reference that provisioner - eliminating the need to deploy EG entirely.  

(I used double-quotes in the last link because that work is quite experimental.  However, when implementing provisioners I used the "Kubernetes Provisioner" as a proof of concept and there would likely be a number of "touch-ups" required. )

Since kernel provisioners are the direction we should be taking, I would recommend that approach be adopted. 

I hope that helps.

FYI - the remote provisioners in the linked repo are essentially manifestations of EG's process proxies, but, with kernel provisioners, fit into Jupyter stack in a much cleaner manner.

**Comment by elibixby** [comment]
@kevin-bates Thanks for your detailed reply! Kernel provisioners do indeed look like the right solution for me, and much more lightweight  than a sidecar container. 

Is your Kubernetes provisioner going to evolve into a separate library included by EG? I was looking for a way to pull the core kernel deployment logic out of EG to do something similar and it looked daunting (hence the sidecar idea), but it would be awesome if both EG, and users who wanted a provisioner for singleuser notebooks shared this code.

**Comment by kevin-bates** [comment]
The idea would be that provisioners would be provided from separate packages (and likely repositories).  I'm not sure how these repos would be structured, but they'd likely exist in the jupyter_server organization (where EG and JKG will be relocated - probably early next year).  All of the EG process-proxies (like the remote-provisioners I've pointed you to - which are essentially process-proxies re-imagined) share common code and I'd like to keep it that way, but I don't want to imply that _all_ remote provisioners be based on this particular framework (if that makes sense).

> but it would be awesome if both EG, and users who wanted a provisioner for singleuser notebooks shared this code.

Yes, this is the idea behind provisioners - any Jupyter-based application that relies on `jupyter_client` for its kernel management could leverage provisioners - local or remote.  Keep in mind though, that some remote provisioners (particularly those originating from process proxies) require that the kernel resides within the same network as the launching process (i.e., server).  So, if the use-case is one where the user's notebook server resides _outside_ a managed cluster, then there will be a need for a gateway server (JKG or JEG) which essentially decouples the user server from the "kernel server".  Since your use-case uses a notebook server within a managed cluster, then you should be able to leverage provisioners directly.
