### ISSUE TITLE
public_key is missing during starting a new kernel

### ISSUE THREAD

**Issue by roma-glushko** [jupyter/enterprise_gateway#1023]
## Description

I'm trying to marry Enterprise Gateway 2.5.2 (EG) with Z2K JupyterHub setup. However, I have noticed that EG doesn't pass public_key when staring a new kernel which triggers an error both in JupyterLab and K8S logs.

I have also tried to use version 2.2.0 as well as dev one and they worked for me.

Was not able to find any good reason for this. Any clues?

## Screenshots / Logs

<img width="1474" alt="Screen Shot 2022-01-14 at 14 39 05" src="https://user-images.githubusercontent.com/9402690/149516824-0ff2e1dc-4a55-4a13-a067-9c55de2038e6.png">

<img width="1791" alt="Screen Shot 2022-01-14 at 14 38 35" src="https://user-images.githubusercontent.com/9402690/149516842-3517b547-7a1e-4eca-b3cc-e998235a9012.png">

## Environment

- Enterprise Gateway Version 2.5.2
- Platform: Kubernetes
- [Zero to JupyterHub K8S 1.2.0](https://github.com/jupyterhub/zero-to-jupyterhub-k8s)

**Comment by kevin-bates** [comment]
Hi @roma-glushko,

Based on your screen shot, I see the response address port is more of a random port number rather than the 8877 we "pin" in the switch to use a [single response address](https://github.com/jupyter/enterprise_gateway/pull/877) (where we introduce `--public-key`).  Are you setting [`EG_RESPONSE_PORT`](https://github.com/jupyter/enterprise_gateway/blob/1a529b13f3d9ab94411e4751d4bd35bafd6bbc2e/enterprise_gateway/services/processproxies/processproxy.py#L55) to `49583`?  If not, then this would imply the EG that's running is not built from master where this logic and those [_normalized kernel launcher arguments_](https://github.com/jupyter/enterprise_gateway/pull/988) reside.  So I would guess you're using updated kernel images (dev) but a released EG.  Can you verify the kernel image tags and the EG release?  This implies you're running dev-based kernel images with an officially released EG image.

**Comment by roma-glushko** [comment]
@kevin-bates thank you for the response!

It makes sense to double check version mismatch in my custom builds of EG and kernels images.

However, is this mismatch possible if I just used `elyra/enterprise-gateway:2.5.2` (https://github.com/jupyter/enterprise_gateway/blob/master/etc/kubernetes/helm/enterprise-gateway/values.yaml#L2) version in the charts? I assumed that the EG image should already include the right versions of kernelspecs, hence, the right version of commands and kernel images. Does this make sense?

**Comment by kevin-bates** [comment]
Crap - it looks like the 2.5.2 EG was built with references to dev-tagged kernel images!  Looking in the image, I see the following `kernel.json` located in `/usr/local/share/jupyter/kernels/python_kubernetes`:
```
jovyan@bf3555abb854:/usr/local/share/jupyter/kernels/python_kubernetes$ cat kernel.json 
{
  "language": "python",
  "display_name": "Python on Kubernetes",
  "metadata": {
    "process_proxy": {
      "class_name": "enterprise_gateway.services.processproxies.k8s.KubernetesProcessProxy",
      "config": {
        "image_name": "elyra/kernel-py:dev"
      }
    }
  },
  "env": {
  },
  "argv": [
    "python",
    "/usr/local/share/jupyter/kernels/python_kubernetes/scripts/launch_kubernetes.py",
    "--RemoteProcessProxy.kernel-id",
    "{kernel_id}",
    "--RemoteProcessProxy.port-range",
    "{port_range}",
    "--RemoteProcessProxy.response-address",
    "{response_address}"
  ]
}
```

I would recommend you use an NFS mount (or equivalent) for `/usr/local/share/jupyter/kernels`  that contains properly tagged kernel images (e.g., `elyra/kernel-py:2.5.2`) until we can build another EG image with matching kernel specs.

My apologies.

**Comment by roma-glushko** [comment]
@kevin-bates no problem Kevin! Thank you for investigation 👍 
Your advice about kernel/EG version mismatch helped me to build my own version of images. So thank you so much for that <3

**Comment by kevin-bates** [comment]
That's great news @roma-glushko!  So are you moving forward?  (This would help me assess the urgency.)

**Comment by roma-glushko** [comment]
@kevin-bates yes, no rush with this one, please.

**Comment by kevin-bates** [comment]
I've updated the kernelspecs in the `docker.io/elyra/enterprise-gateway:2.5.2` as well as the applicable assets tied to the [release](https://github.com/jupyter/enterprise_gateway/releases/tag/v2.5.2).  As a result, I think we can close this issue.  Thank you @roma-glushko for raising this!
