### ISSUE TITLE
Can we add kernelspecs for kernels with spark standalone mode also. 

### ISSUE THREAD

**Issue by agsachin** [jupyter/enterprise_gateway#346]
Can we add standalone specs using both LocalProcessProxy(default proxy) and DistributedProcessProxy.
https://github.com/jupyter-incubator/enterprise_gateway/tree/master/etc/kernelspecs	
spark_R_standalone
spark_python_standalone
spark_scala_standalone

**Comment by kevin-bates** [comment]
Note that this is now documented in our docs: https://jupyter-enterprise-gateway.readthedocs.io/en/latest/kernel-spark-standalone.html

Since kernelspecs, especially those that are Spark-based, require customizations to each environment, and to reduce the support matrix involved in maintaining physical copies that differ slightly from the YARN client deliverables, I'm closing this issue.

When addressing issue #654 or #655, we can be sure to add a standalone option, but for now I think the documentation should prove sufficient.
