### ISSUE TITLE
Update vanilla python kernel docker image to be based on Anaconda

### ISSUE THREAD

**Issue by lresende** [jupyter/enterprise_gateway#367]
Current we have all kernel docker images based on the spark images. We should continue to have these, which would be used by Spark on Kubernetes support, but the vanilla ones we should base on anaconda to make it much simpler for data scientists to use these as bases for their work.

**Comment by kevin-bates** [comment]
After discussion with @lresende - each of the kernel image files (for vanilla - non-spark modes) will have different bases.  The R kernel will be based on the jupyter/r-notebook image, with any additional packages needed to address R-kernel-launcher dependencies.  

Likewise, since Toree (Scala) is tied so heavily to Spark, we'll likely use the current approach of a shared image with different `CMD` startups.  

It makes sense to base the vanilla python image on anaconda - as was the intention here.  As a result, I'm going to rename this issue and create separate issues for R and Scala vanilla images.

**Comment by kevin-bates** [comment]
Naming conventions (note, we may convert `kubernetes-` to `k8s-` at some point.

Vanilla:  `elyra/kubernetes-kernel-{python,r,scala}`
Spark: `elyra/kubernetes-spark-kernel-{python,r,scala}`

although these conventions are open for discussion.
