### ISSUE TITLE
Interaction between Jupyter Lab and launched kernels via Enterprise Gateway

### ISSUE THREAD

**Issue by amangarg96** [jupyter/enterprise_gateway#455]
I launched an IPython kernel on a Spark Cluster using Jupyter Enterprise Gateway. After launching the kernel, I stopped Jupyter Enterprise Gateway server (using `kill -9 <pid>`). I could still see the kernel in running state on Spark, but the Notebook server wasn't able to use the kernel. Is this expected behaviour? 

As per my understanding, the Jupyter Enterprise Gateway launches the remote kernel on Spark and then sends the connection info json file to the Notebook server. Once the connection has been established between the Notebook Server and the Kernel through the 5 ZMQ ports, it shouldn't be requiring the Enterprise Gateway to be running.

**Comment by kevin-bates** [comment]
Yes, that behavior is expected.  Enterprise Gateway (like Kernel Gateway) services the `/api/kernels` and `/api/kernelspecs` endpoints.  As a result, it is  required to communicate with the kernel.  

To properly shutdown Enterprise Gateway, use `kill <pid>` or `kill -15 <pid>` (SIGTERM) so that an attempt to shutdown running kernels is performed.  (I know you used SIGKILL to complete your experiment - this comment is more for the sake of others.)

Although the channels traffic (kernel messages) is essentially forwarded to its super classes (notebook server), Enterprise Gateway intercepts kernel lifecycle management functions (including interrupts) in order to start, shutdown, and interrupt remote kernels.
