### ISSUE TITLE
Improve upon base libraries in Spark-based kernel images and ensure custom libs can be installed.

### ISSUE THREAD

**Issue by rayh** [jupyter/enterprise_gateway#522]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/57468/49704652-c021b400-fc69-11e8-9adf-2ba6cc049e94.png">

Would be good to have a predefined list of packages for R + Spark, but we should be able to install packages at run-time is need be.

**Comment by kevin-bates** [comment]
I agree to both counts.  Let's add `sparklyr` to the `kernel-spark-r` Dockerfile and fix the installation issue.

Do you have suggestions for other packages?  I'm asking this for python and scala images as well?

**Comment by rayh** [comment]
I think the R library folder just needs to be chown'd:

```
RUN adduser -S -u 1000 -G users jovyan && \
	chown -R jovyan:users \
    /usr/local/share/jupyter \
    /opt/spark/work-dir \
    ${R_HOME}/library
```

**Comment by rayh** [comment]
As for R packages, this is a set of libraries we use:

```
install.packages(c(
  'tidyverse',
  'keras',
  'cloudml',
  'base64enc',
  'drat',
  'RJSONIO',
  'itertools',
  'digest',
  'Rcpp',
  'functional',
  'plyr',
  'reshape2',
  'caTools',
  'DBI',
  'R.methodsS3',
  'Hmisc',
  'memoise',
  'rjson',
  'sparklyr',
  'shiny',
  'rmarkdown',
  'leaflet',
  'geojsonio',
  'sf',
  'zip',
  'argparser',
  'jsonlite',
  'uuid',
  'stringr',
  'repr',
  'IRkernel',
  'IRdisplay',
  'evaluate',
  'crayon',
  'pbdZMQ',
  'digest',
  'base64enc',
  'versions'
), repos="http://cran.cnr.berkeley.edu")

install.packages(c(
  'awspack',
  'bigQueryR',
  'googleAuthR',
  'googleCloudStorageR',
  'rdatastore',
  'googleComputeEngineR',
  'RoogleVision'
), repos = c(cloudyr = "http://cloudyr.github.io/drat"))

versions::install.versions('devtools', '1.13.6', lib='/usr/lib/R/library')
```

**Comment by kevin-bates** [comment]
Thanks @rayh.  I think the CRAN libraries look fine and seems we should ensure our kernel*-r images contains those packages.  The ones from `cloudyr.github.io/drat` look a little company-specific (aws, google) and I'm hesitant to add those packages.  The idea would be that people/companies create images from those we provide.  I'd prefer we not go do a path where our images have the union of everyone's needs.

Do you know if there are other open-source images that contain those sets of packages (from the second set)?  I'm just trying to get an idea of how widespread they are.  I'm kinda inclined to constrain our images to CRAN.

What do others think?

**Comment by kevin-bates** [comment]
@rayh - in talking with @lresende, he reminded me that are "cut-off" wrt libraries in images was going to be conda. (at least for python and R).  If we do that, will that provide you with an adequate base of libraries?  

@akchinSTC - do you mind looking into this?  The directory permissions require modification and we should probably beef up the libraries installations in the kernel-spark-r and kernel-spark-py images since, at this moment, they're really just basic spark images.

It seems best to simply use our kernel-r and kernel-py images as the base images for the corresponding spark images, but I don't know what it takes to actually get spark installed for use in k8s w/o digging into the image build script referenced in https://hub.docker.com/r/elyra/spark-py/.

**Comment by rayh** [comment]
Conda is fine - whatever it can provide.  but does that mean we'd have to use conda to install additional packages rather than install.packages() ?

**Comment by kevin-bates** [comment]
I would hope that's not the case.  I'm assuming it would work similar to conda and pip, but I'm relatively new to those language domains.

**Comment by akchinSTC** [comment]
The base R image that is referenced in upstream spark does contain a basic installation of R and R-dev packages. Suggest removing the existing install and replacing it with mini-conda and base R libs to provide the same functionality and avoid confusion. @rayh - You should be able to continue using CRAN to install your packages via install.packages.

**Comment by lresende** [comment]
> @rayh - in talking with @lresende, he reminded me that are "cut-off" wrt libraries in images was going to be conda. (at least for python and R). If we do that, will that provide you with an adequate base of libraries?
> 

I believe the first thing we should fix is to enable users to install their own packages, as we will never have the necessary packages for every single user. Here is a good start point to some env we should set on our R kernel image: https://www.r-bloggers.com/installing-r-packages/

> @akchinSTC - do you mind looking into this? The directory permissions require modification and we should probably beef up the libraries installations in the kernel-spark-r and kernel-spark-py images since, at this moment, they're really just basic spark images.

For now, can we make sure we have users able to install their required packages from the notebook for both python and r.

> 
> It seems best to simply use our kernel-r and kernel-py images as the base images for the corresponding spark images, but I don't know what it takes to actually get spark installed for use in k8s w/o digging into the image build script referenced in https://hub.docker.com/r/elyra/spark-py/.

Now, for what to install, we should probably come up with a good base image for each language and document it for users to actually validate and then we implement. More like a survey. We should consider regular users and also enterprise users. Otherwise, we will keep modifying the base images very frequently. 

The other aspect is that we should also make it simpler for users to bring their own images, so they can make any customizations that they require.

**Comment by lresende** [comment]
> As for R packages, this is a set of libraries we use:
> 
> ```
> install.packages(c(
>   'tidyverse',
>   'keras',
>   'cloudml',
>   'base64enc',
>   'drat',
>   'RJSONIO',
>   'itertools',
>   'digest',
>   'Rcpp',
>   'functional',
>   'plyr',
>   'reshape2',
>   'caTools',
>   'DBI',
>   'R.methodsS3',
>   'Hmisc',
>   'memoise',
>   'rjson',
>   'sparklyr',
>   'shiny',
>   'rmarkdown',
>   'leaflet',
>   'geojsonio',
>   'sf',
>   'zip',
>   'argparser',
>   'jsonlite',
>   'uuid',
>   'stringr',
>   'repr',
>   'IRkernel',
>   'IRdisplay',
>   'evaluate',
>   'crayon',
>   'pbdZMQ',
>   'digest',
>   'base64enc',
>   'versions'
> ), repos="http://cran.cnr.berkeley.edu")
> 
> install.packages(c(
>   'awspack',
>   'bigQueryR',
>   'googleAuthR',
>   'googleCloudStorageR',
>   'rdatastore',
>   'googleComputeEngineR',
>   'RoogleVision'
> ), repos = c(cloudyr = "http://cloudyr.github.io/drat"))
> 
> versions::install.versions('devtools', '1.13.6', lib='/usr/lib/R/library')
> ```

Thanks a lot @rayh . @akchinSTC We should use a version of this as the base list, and maybe consult with the members of R consortium (@gdequeiroz) in our extended team for their opinion/additions.

**Comment by rayh** [comment]
@akchinSTC that list looks good - i'd just add tidyverse as well as sparklyr to that.  

While it's good to let people install their own packages, if they have to do this every time the kernel starts, then it's going to be very frustrating as those R packages usually compile from source.  Having said that, I'm not suggesting we fix R's package installation performance issues, just that we make that base image as generally useful as possible.

**Comment by rayh** [comment]
I've started forking our own images for the kernels, I've baked in a copy of kernel-launchers for now.  I'll update here with a reference once I've got something working.

This will include a base set of libraries for python and R using conda as much as possible, but falling back to install.packages() if/when conda doesnt have availability/.

**Comment by rayh** [comment]
See my comment: https://github.com/jupyter/enterprise_gateway/issues/526#issuecomment-448489301 - I've added libraries to both the python and R kernels as well as allowing the user to add their own (via conda).
