### ISSUE TITLE
Download of Image Files Fails

### ISSUE THREAD

**Issue by bashterm** [jupyter/enterprise_gateway#549]
It says [here](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-kernels.html) in the documentation that kernel image files can be downloaded form the address: 

`https://github.com/jupyter/enterprise_gateway/releases/download/v2.0.0.dev0/jupyter_enterprise_gateway_kernelspecs-2.0.0.dev0.tar.gz`

However when I go to download them I get a 404 Not Found.

**Comment by kevin-bates** [comment]
Hi Aidan.  This is expected since we need to publish a release for anything in the upcoming release to be effective.  When I produced the doc update, I figured we were a day or two from building the release - who would know.  :smiley:  We're (finally) in the process of building `2.0.0.b1` and will update the link (and resolve the issue) once this is ready.

Sorry for the inconvenience.

**Comment by kevin-bates** [comment]
Our first 2.0.0 beta release is out: https://github.com/jupyter/enterprise_gateway/releases/tag/v2.0.0-beta.1

You can download the kernel-image-files tar using: https://github.com/jupyter/enterprise_gateway/releases/download/v2.0.0-beta.1/jupyter_enterprise_gateway_kernel_image_files-2.0.0.b1.tar.gz
