### ISSUE TITLE
Failed to start kernel if username contains .

### ISSUE THREAD

**Issue by ktong** [jupyter/enterprise_gateway#553]
As name of namespace only allows lower case alphanumber and -, it has to rewrite user name by change L164 to:

namespace = re.sub('[^0-9a-z]+', '-', kernel_username).lower() + '-' + self.kernel_id

https://github.com/jupyter/enterprise_gateway/blob/69807950e4bff399bb73ac41f74cf6be4b4b055a/enterprise_gateway/services/processproxies/k8s.py#L164

**Comment by kevin-bates** [comment]
@esevan - thanks for the reference.  This makes sense and came in just as I was submitting my opinion on the PR.  

Because namespaces cannot start with '-' and that is the escape character, we'd need to handle that as well.  

I'm okay either way.  It would be nice to follow JupyterHub's lead - so I suppose I'm leaning toward that.  However, we should probably check for a leading '-' BEFORE performing the DNS adjustment and I don't think we have any choice in that case but to drop a leading dash '-'.

What do you folks think?

**Comment by esevan** [comment]
What about urlencode approach (It's motivated by JupyterHub PVC creation mechanism)?

1. Non-safe characters is not replaced by `-`, but urlencoded with `-` instead of `%` to decode it properly.
  e.g. esevan.park -> esevan-2epark
2. In just few cases, there're `-` leading user name (never seen this before). Just remove dashes.

**Comment by kevin-bates** [comment]
@ktong, @esevan - Please disregard my previous comment about moving the modification of kernel-username to the session manager.  This will side affect all other process proxy behaviors.  Since this issue only applies to kubernetes (I confirmed docker can create containers with _dotted_ names), I think we need to something like the following.

Introduce `KERNEL_POD_NAME` to the kwargs['env'] dict.  This would be initialized in a new method like `_determine_kernel_pod_name()` that sets `self.kernel_pod_name` just prior to [this method call](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/k8s.py#L42).  This method would apply the DNS constraints.  The method would then add `KERNEL_POD_NAME` to the envs, similar to what `_determine_kernel_namespace()` does.

Then, `_determine_kernel_namespace()` would just use `self.kernel_pod_name` in the location where it needs to construct the name.

Finally, we'd need to update [kernel-pod.yaml](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml) and replace the two occurrences of `${kernel_username}-${kernel_id}` with `${kernel_pod_name}`.

I'm sorry about all the switching around.  I just want to make sure we don't interfere with valid usernames on process proxies where we use the name for impersonation, etc.

It would be great if you could contribute these changes, but, if you'd rather not, I'd be happy to get them in.  Please let me know.

Thank you.

**Comment by kevin-bates** [comment]
No worries Kuisong.  Enjoy your travels and thanks again for the contributions.

**Comment by ktong** [comment]
the logic for determine name of namespace is in method _create_kernel_namespace. So it needs more refactor to use new created kernel_pod_name. Need more consideration for PR.

**Comment by kevin-bates** [comment]
>the logic for determine name of namespace is in method _create_kernel_namespace. So it needs more refactor to use new created kernel_pod_name. Need more consideration for PR.

The idea I gave above would be that [this line](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/k8s.py#L164) would be replaced with: `namespace = self.kernel_pod_name`.  Looks like we could drop the `kernel_username` parameter as well.

>By the way, the service_account_name generated in _determine_kernel_service_account_name does not use in _create_kernel_namespace, could we delete the logic?

Hmm, I see the `service_account_name` used when [creating the role binding](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/k8s.py#L180).  I think we still need that parameter.

**Comment by ktong** [comment]
change pushed
