### ISSUE TITLE
how to use nbconvert ? 

### ISSUE THREAD

**Issue by gem874** [jupyter/enterprise_gateway#577]
Hello, I have a questions. 
I can't use nbconvert command. Please check below. 

[ Setting ] 
* Pythons 3.7 
* Setting & install 
  Jupyter notebook(ver. 5.7.0) , nb2kg (ver. 0.3.0) and enterprise gateway (ver 1.1.1 ) in spark master yarn

[ Step ]
* Create notebook file and source code using jupyter notebook: mynotebook.ipynb
  (Spark - Python (YARN Client Mode))
* Execute command line : jupyter nbconvert --ExecutePreprocessor.kernel_name=spark_python_yarn_cluster --to notebook --execute --inplace mynotebook.ipynb 

[Error messages] 
* Can't find kernel ID.  : ERROR__NO__KERNEL_ID

When I run command line, i see these errors.  How can i use do that ? or any other method ?

**Comment by kevin-bates** [comment]
Hello - thank you for your question.

Having just looked at the `nbconvert` today, it looks like it only relies on kernel management from jupyter_client.  It does provide the ability to specify an override for the KernelManager class (similar to how Notebook is invoked when the NB2KG extension is configured), but only the `start_kernel()` method is supported via NB2KG.  However, after the kernel manager instance is created, it calls its `client()` method to access the channels (zmq ports) and the client() method is not proxied via NB2KG.

So, without added the ability to fully remote the kernel operations you'll need to execute the notebook using Notebook (with NB2KG).  If you wanted to convert to a different format, you still have a couple choices...

1. Run `nbconvert` against the saved notebook file where it only operates against its content and doesn't enlist the services of the kernel used to produce the notebook's output (e.g., `jupyter nbconvert python\ -\ yarn\ cluster.ipynb --to pdf`)
2. Use `Download as...` in the notebook File menu while you're running the remote kernel.  This will utilize the local laTeX resources to perform the conversion  (e.g., [python - yarn cluster.pdf](https://github.com/jupyter/enterprise_gateway/files/2856988/python.-.yarn.cluster.pdf))

I hope that helps move you forward.

P.S., I notice above you created the notebook using the YARN **Client** Mode but wanted YARN **Cluster** Mode as your kernel via nbconvert.  Was that change intentional?

**Comment by gem874** [comment]
Hello thank you for reply. 
Sorry, I mistake the word. I use  "Spark - Python (YARN Cluster Mode))".   :) 

I want to batch everyday for reporting. 
So, I create ".* ipynb" file and schedule using airflow. 

Airflow maybe run these command per schedule-interval. 
* command :  jupyter nbconvert --ExecutePreprocessor.kernel_name=spark_python_yarn_cluster --to notebook --execute --inplace mynotebook.ipynb

[ Question 1. ]
How can I add ability to fully remote the kernel operations ? 

[ Question 2. ]
And I have another question. Do you know Livy? If you know Livy, please check my question. 
What is different Livy compare to Enterprise Gateway?  
Does it have the ability to distribute kernel resource ? 

When I see document about Enterprise Gateway. I understand Enterprise Gateway functionality. 
1. Can use yarn cluster kernel to communicate.
2. Distribute jupyter kernel resource. 
* Reference :  https://www.slideshare.net/luckbr1975/jupyter-enterprise-gateway-overview

Apache Livy is a service that enables easy interaction with a Spark cluster over a REST interface.
In this situation, why should I use Enterprise Gateway ?

**Comment by gem874** [comment]
Please reference Q1. 

[Command] 
> jupyter nbconvert 
--ExecutePreprocessor.kernel_name=spark_python_yarn_cluster 
--ExecutePreprocessor.kernel_manager_class=enterprise_gateway.services.kernels.remotemanager.RemoteMappingKernelManager 
--execute 
--to notebook /opt/jupyter/source/spark_cluster.ipynb 
--ServePostProcessor.ip=10.100.0.243 
--debug

[ Error Message ] 
> Future exception was never retrieved
future: <Future finished exception=KeyError('kernel_name')>
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 30, in start_kernel
    format(kernel_name=kwargs['kernel_name'], username=username))
KeyError: 'kernel_name'
Traceback (most recent call last):
  File "/usr/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 337, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 507, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 478, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 407, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 178, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 196, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 138, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 315, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 359, in preprocess
    with self.setup_preprocessor(nb, resources, km=km):
  File "/usr/lib64/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 304, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(cwd=path)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 255, in start_new_kernel
    kc = km.client()
AttributeError: 'RemoteMappingKernelManager' object has no attribute 'client'

**Comment by lresende** [comment]
> Hello thank you for reply.
> Sorry, I mistake the word. I use "Spark - Python (YARN Cluster Mode))". :)
> 
> I want to batch everyday for reporting.
> So, I create ".* ipynb" file and schedule using airflow.
> 
> Airflow maybe run these command per schedule-interval.
> 
>     * command :  jupyter nbconvert --ExecutePreprocessor.kernel_name=spark_python_yarn_cluster --to notebook --execute --inplace mynotebook.ipynb
> 
> 
> [ Question 1. ]
> How can I add ability to fully remote the kernel operations ?
> 

Not with NbConvert. If you require 'cluster mode'  you have to interface programmatically with Jupyter Enterprise Gateway, if you can live with 'client mode' you might be able to use something like papermill. 

For accomplishing the execution interfacing with Enterprise Gateway, take a look at [this example](https://github.com/lresende/eg-sentiment-microservice-demo), whith the caveat that we have made a [gateway client experimental utility](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/client/gateway_client.py) that can minimize the code you need to write in order to communicate with the gateway server

> [ Question 2. ]
> And I have another question. Do you know Livy? If you know Livy, please check my question.
> What is different Livy compare to Enterprise Gateway?
Enterprise Gateway provides a Jupyter based native solution and is not focused ONLY on spark, while Livy is focused on supporting YARN use case and wasn't designed for Jupyter Notebooks.

> Does it have the ability to distribute kernel resource ?
I don't know if the latest Livy release has support for 'cluster mode'.
> 
> When I see document about Enterprise Gateway. I understand Enterprise Gateway functionality.
>     1. Can use yarn cluster kernel to communicate.
>     2. Distribute jupyter kernel resource.
> 

Yes, Enterprise Gateway supports YARN cluster mode, which will distribute your kernel in a YARN cluster. In this case, because the kernel is launched remotely, the gateway then has to discover the location of the kernel as well as any other configurations used (e.g. ports) to enable Jupyter Notebooks or other clients to communicate with the kernel.

> 
>     * Reference :  https://www.slideshare.net/luckbr1975/jupyter-enterprise-gateway-overview
> 
> 
> Apache Livy is a service that enables easy interaction with a Spark cluster over a REST interface.
> In this situation, why should I use Enterprise Gateway ?
> 

For running Jupyter Notebooks, you will have the full support of all magic, and other Jupyter specific functionality using Enterprise Gateway, which is built on top of the Jupyter Stack from the beginning. This enables you to develop and validate your notebook code in the notebook UI, and then schedule it with some kind of backend utility and make sure it will work as expected as it's using the same underlying infrastructure to run the scheduled notebook.

> [ Question 3. ]
> Or.. Can I change this command to nbconvert ?
> 
> > jupyter notebook 
> >   --NotebookApp.session_manager_class=nb2kg.managers.SessionManager 
> >   --NotebookApp.kernel_manager_class=nb2kg.managers.RemoteKernelManager 
> >   --NotebookApp.kernel_spec_manager_class=nb2kg.managers.RemoteKernelSpecManager

I have not really tried to integrate nbconvert with enterprise gateway, and I would recommend using the approach described above as the answer to your question 1.

**Comment by gem874** [comment]
Hello, thank u for answer. 
I decided that. 
1. Make summary data with spark yarn kernel  (.py / master installed enterprise gateway) 
2. Save summary data to some RDB 
3. Make notebook file to create reporting file 
( This file connect RDB and make report. It doesn't need to use cluster kernel) 
4. Run nbconvert in jupyter server using jupyter local kernel)

**Comment by kevin-bates** [comment]
This is great info for the benefit of others - thank you for the update.
