### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by witten** [jupyter/enterprise_gateway#625]
It would be great to have an officially supported [Helm](https://helm.sh/) chart for the Kubernetes version of Jupyter Enterprise Gateway. For Kubernetes + Helm users, that would unlock a more structured and on-the-rails mechanism for packaging and distributing the gateway, setting individual variables like `EG_NAMESPACE`, deploying the gateway, etc. At least compared to the current approach of checking out source, hacking directly on YAML template files, and running `kubectl apply`.

**Comment by kevin-bates** [comment]
@witten - this is a great idea.  Would you be willing to take stab at this?  

I'm not familiar with Helm - but it would probably be good to model _conventions_ (if that's applicable) after the charts used for JupyterHub.

**Comment by witten** [comment]
Possibly.. It depends whether my organization ends up adopting Jupyter Enterprise Gateway! If we do, we'll need a Helm chart. And if there isn't one by then, we'd be happy to create one and share it here.

**Comment by kevin-bates** [comment]
Excellent!  So how can we help your organization adopt Enterprise Gateway? 😃

Please feel free to ask questions and discuss various topics on our [discourse category](https://discourse.jupyter.org/c/enterprise-gateway) or [gitter room](https://gitter.im/jupyter/enterprise_gateway).  For more sensitive discussions we would be happy to have a call in order to help move things forward for you and your organization.

**Comment by witten** [comment]
I think it's about two things: 1. We need to free up the internal development bandwidth to drive adoption. That's strictly on us. 2. Once we do that, we can try to integrate Enterprise Gateway with our stack and workflow. That's where I think it's likely that we'll have questions or feature requests that you may be able to help out with or at least weigh in on.

For number 2, here's an example. We use HDFS, with uses Kerberos, which requires a custom Docker image for use with Spark. If/when we get to the point of trying that out, we may request help with with using custom Spark Docker images with Enterprise Gateway.

Thanks though for your offer to help out! That's much appreciated.

**Comment by kevin-bates** [comment]
Sounds good.

Regarding your custom Docker image, this should be a matter of getting the kernel-launcher files installed and then ensuring your [image references are updated in your kernelspec](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernelspecs/spark_python_kubernetes/kernel.json#L8-L9).  Although our [doc](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/docker.html#custom-kernel-images) doesn't show an example of a spark-based image (since those are quite a bit different since the launch occurs via `spark-submit`), it does show how you'd go about installing the kernel-launchers.  This, coupled with using [spark_python_kubernetes kernelspec](https://github.com/jupyter/enterprise_gateway/tree/master/etc/kernelspecs/spark_python_kubernetes) as example, should get you going.

**Comment by witten** [comment]
Awesome, thanks!

**Comment by witten** [comment]
So, I lied. I took a stab at this: https://github.com/jupyter/enterprise_gateway/pull/628
