### ISSUE TITLE
Handling different projects with different conda envs or pipenv

### ISSUE THREAD

**Issue by SolarisYan** [jupyter/enterprise_gateway#649]
Hi there, this feature request is from https://github.com/jupyter/help/issues/342 , I think this is a cool function, can we get that with enterprise-gateway?

**Comment by kevin-bates** [comment]
Can you please be more specific?  There appear to be two primary items here - 1) discovering kernels from different environments and 2) changing the tab in the UI to reflect the lab build.  Both of these are fairly tightly coupled with self-contained, local-only Notebook and kernel operations.

Since EG is separate from the client notebook/lab instance, I suspect 2) is not an issue.  What happens on the client side is independent of EG - so long as the kernel ops get proxied to the gateway.

Regarding 1), kernels are also remote from EG.  As a result, the env the kernel is run is purely a function of what the kernelspec does and how additional items are configured via the underlying process-proxy.

Our sample kernelspecs that we provide OOTB are typically installed in env-neutral locations (e.g., `/usr/local/share/jupyter/kernels`) that are on the default search path.  This results in the potential for varying "conda envs" from being discovered.

**Comment by SolarisYan** [comment]
@kevin-bates Thank you for response, I have not thought about this issue clearly.

**Comment by kevin-bates** [comment]
Just re-read the original feature request and I should add that EG is itself a Jupyter Application (that is, it's main class derives from `JupyterApp`).  As a result, it can leverage whatever configuration related functionality mentioned in the original feature request.  However, because we recommend our OOTB kernelspecs be placed in conda-env-neutral locations, they should be available to all envs.  Not sure if that helps this discussion along or not.

**Comment by kevin-bates** [comment]
I believe this discussion has reached a conclusion - closing the issue.  Please re-open if that action is warranted.
