### ISSUE TITLE
Kernel startup error message when YARN queue is full.

### ISSUE THREAD

**Issue by amangarg96** [jupyter/enterprise_gateway#664]
I'm using Jupyter Enterprise Gateway in YARN cluster mode.

When a kernel is launched and the YARN queue is full, the spark job remains in 'ACCEPTED' state and waits for the resources to be available. After a while, if the resources are still not available (I'm guessing after the `KG_REQUEST_TIMEOUT`), the notebook shows `HTTP 504: Gateway Timeout` error. 

This Spark job becomes an orphan job which remains in the ACCEPTED state and goes into RUNNING state once the resources are available. 

So there are two problems which arise in such a scenario:
1. The orphan spark-job which now cannot be killed by Jupyter Enterprise Gateway
2. User does not get to know that the resources are not available.

What should be the solution for these? 
One way could be to get the status of the queue before the kernel launch, and if queue is full show an error message saying resources are not available (without attempting to launch the kernel)

**Comment by kevin-bates** [comment]
Yes - this is an issue.  The actual timeout with regard to YARN is the `KERNEL_LAUNCH_TIMEOUT` value, but that should always be less than `KG_REQUEST_TIMEOUT`.  I think your suggestion of checking the queue prior to launch sounds reasonable.  There will be race conditions with that, but I'm not certain what the alternatives would be.  The installation should configure the two timeout values to be relative to _tolerance levels_.  This issue is also a function of the granularity of the tasks.  I.e., if only kernels are running, those will tend to be more _consuming_ than generic tasks.

Are you able to contribute this kind of change?  If so, it might require changes to the [yarn-api-client package](https://github.com/toidi/hadoop-yarn-api-python-client) that EG uses in order to check the queue. We'll be happy to help you guide you should you need any assistance.

**Comment by amangarg96** [comment]
Yes, the race conditions is something which crossed my mind too. But would be much rarer than the current problem so ignoring it would still be a good improvement.

I did not understand the tolerance levels part and the granularity of the tasks part. Could you throw some more light on it?

**Comment by kevin-bates** [comment]
Sorry - I should have clarified these.  By _tolerance levels_, I mean the number of seconds a given installation is tolerating for the two forms - idle and busy.  In some cases, installations may make each the same (which is essentially addressed by the current implementation).

By _granularity of the tasks_ I mean that things like native Spark applications will be much finer-grained.  There are no humans sitting at a terminal where the YARN resource is being consumed waiting for a key-stroke.  So if the installation only runs Spark jobs on behalf of kernels, those Spark jobs will tend to be more consuming with respect to YARN resource management.  If there are fewer kernels relative to native Spark jobs, then the tolerance levels could be higher because there are fewer kernels competing for the YARN job slots.

So the point I'm making is that even if we check the queue and the queue comes back full, the question to ask is "Will a slot open up soon enough such that the kernel could start before the `KERNEL_LAUNCH_TIMEOUT`".  

(Hmm - this just occurred to me... This implies that perhaps we could take a small percentage of the `KERNEL_LAUNCH_TIMEOUT` value and, if the queue is full, take that amount of time to periodically check the queue, before failing the start request due to a full queue.  If `KERNEL_LAUNCH_TIMEOUT` is `40`, take 10-20% (4 to 8 seconds) re-checking the queue before giving up.  In this case, the request would fail in 4-8 seconds, rather than 1 or 2 if only one check was performed.  However, if the queue does open up, we'd need to complete the request in the allotted time.)

**Comment by IMAM9AIS** [comment]
We are able to check the capacity of the queue with few changes in yarn-api-client package. Following this we will be able to NOT submit the the job to YARN cluster. 

But we need to propagate back this information to the client, for this to be meaningful. 
How can this be achieved  and which part of the code should i be looking at for this ? 
Will self.log_and_raise() be the best candidate for this ?

**Comment by kevin-bates** [comment]
Excellent.  Yeah, I suspect `log_and_raise` (as you're original response suggested) is the best we can do.  This is an area where we could use some client-side help from the notebook.  I believe right now, the client will receive a kernel error and the message passed to `log_and_raise` will be in the traceback - which isn't very friendly.

I'm thinking a `503 - Service unavailable` status code is probably best, along with a helpful description.

Given you had edited your original response, did you happen to find issues with using `log_and_raise`, or just wanted the update to be less assuming?

**Comment by IMAM9AIS** [comment]
Oh! I really was not sure if log_and_raise would propagate the error back. (Was Less assuming). 
But thanks for pointing that out. We will make these changes and see if comments propagate back.

You rightly pointed out that the things won't be looking friendly on the client side with the trace back.

Since we are actually using nb2kg package for overriding the calls to be made to gateway, would you suggest looking to write more code in this library to handle the errors being sent.

**Comment by kevin-bates** [comment]
If you don't mind looking into that, that would be fantastic!  

Please keep in mind that as of (the yet to be released) Notebook 6.0, the NB2KG extension is embedded directly into notebook in the [`gateway` "sub-package"](https://github.com/jupyter/notebook/tree/master/notebook/gateway).  As such, should you find that a change to NB2KG is helpful, a similar change may be warranted to the "embedded code-base" as well.

**Comment by IMAM9AIS** [comment]
Hi Kevin,

So we went back and coded the solution for propagating the error back to the lab screen and things seem to work fine. We have also built up the logic of periodically checking the queue for about 20 percent of KERNEL_LAUNCH_TIMEOUT. 

We have some queries regarding the structuring of the code though. Right now we have written all the changes in **yarn.py** file, but it seems logical to move the snippet of confirming yarn queue availability to **yarn-api-client** package. 

But should the logic of periodically checking the availability of yarn queue(20% timeout feature) should also move **yarn-api-client** or can be in **yarn.py** ?

Do let us know what you think of these changes .

**Comment by kevin-bates** [comment]
Hi Imam,

I'm sorry for the delayed response.  I read this in the morning (PDT) then was busy with other things and just now revisited - this is awesome news!

I think you're first instinct is correct...
> to move the snippet of confirming yarn queue availability to yarn-api-client package

I believe the periodic checking - as well as the threshold - is more application specific and should remain in EG (yarn.py).  I'm assuming you're adding this functionality to `handle_timeout()`.

Many of us monitor the [yarn-api-client](https://github.com/toidi/hadoop-yarn-api-python-client) repository so we can assist with any related PR. 

We really look forward to your contribution - thank you!

**Comment by kevin-bates** [comment]
@IMAM9AIS - any update on this?

**Comment by IMAM9AIS** [comment]
Hi Kevin,

So sorry i could not get back on this.
We have indeed coded up the solution and deployed it in our internal systems recently. We are going through an initial level of proof checking before raising a PR on the repo.

We have a couple of questions though :- 

 1. Some of the fixes that we have deployed takes into account the details of our internal yarn queue configurations to parse and understand queue availability scenario . Although we are taking the queue names and labels from kernel.json file, we need some guidance of making this solution generic enough. 

2. We have also created an another fix for kernel launch. Given the clients can request kernels of any memory, we have provided a check to deter clients from launching kernels that have driver memory/executor memory greater than the container size that is configured in our yarn cluster which makes some sense. This change is a generic one where we are fetching conf details for yarn cluster, getting the driver/executor memory from kernel.json and comparing these too. Should we plan to raise this as a PR too or you have other recommendations on this.

**Comment by kevin-bates** [comment]
No worries - this all sounds very exciting!

Until we see the changes, it's tough to make recommendations.  I'm assuming the client-specified memory values are being conveyed via `KERNEL_` values in the env body - which sounds fine.  We might want to standardize suffixes for those names, but I think that's about all we can do prior to fully-defined _parameterized kernels_, which require larger community input (and, thus, time!).

As for pulling/parsing items from the kernel.json, so long as that is occurring in the process proxy, I think that's fine.  In fact, given where things are heading, we should try avoid any updates in `RemoteKernelManager` or potential subclass.  Still, we may want to consider a section in the `metadata` stanza that contains parameters - but all of which could be subject to change.

Actually, you may be extending the `config` section of the `process_proxy` stanza since that's what is passed to the constructors (unless that's one of you modifications), which seems fine as well.

I would recommend submitting a PR.  You can prefix with `[WIP]` and we can iterate on that if you wish.

Thank you!

**Comment by IMAM9AIS** [comment]
Sure. Will be doing this in a couple of days.
