### ISSUE TITLE
More EG instances in single k8s cluster

### ISSUE THREAD

**Issue by michzimny** [jupyter/enterprise_gateway#671]
I'd like to have two separated EG instances in a single k8s cluster. Kernels of both instances are run in separate k8s namespaces.

Are there any known problems in such an approach? Is it discouraged for any reason? Are there any specific config suggestions?

The only issue I see is about orphaned kernels. I've noted that stopping EG pod (e.g. when updating the service with `kubectl apply -f ...`) causes running kernels to stay working. And they stay leaving forever. It seems that culling then does not work for such orphaned kernels (as culling is perhaps done by EG, and the newly created EG pod is not aware of those old kernels, right?). I can delete them manually but it gets complicated when I have two EG instances, because I cannot (?) easily check which kernels are really orphaned. Is there any suggested solution for such orphaned kernels?

**Comment by kevin-bates** [comment]
If you're just trying to run kernels in separate namespaces, that's the default behavior provided by EG.  Kernels will reside in the same namespace only if you specify `KERNEL_NAMESPACE` (along with `KERNEL_SERVICE_ACCOUNT_NAME`) - in which case EG assumes the namespace named in `KERNEL_NAMESPACE` already exists, or if `EG_SHARED_NAMESPACE=True` is specified - in which case all kernels will reside in the namespace in which EG is running (this is not a recommended configuration, but we support that).  Otherwise, by default, EG will create a namespace of the name `<kernel-username>-<kernel_id>` and EG is responsible for removing that namespace upon the kernel's termination.

If you still need to run multiple EG instances, then there are some things you must consider.  
1. We currently don't have support for Active/Active HA. 
2. Our support for Active/Passive HA is limited and requires that EG be invoked with `--KernelSessionManager.enable_persistence=True`.
3. Since this is a docker environment, the persisted session file would require a shared location that EG instances can access.

In this case, when the second EG starts, it would try to connect with any existing entries in the session persistence file.  But the whole HA stuff is in the state of flux right now.

You can also run EG with multiple replicas and, because we configure affinity, a given client will "stick" to a given EG instance.  However, should a replica go down, and session persistence is not properly configured, you'll experience orphaned kernel pods. 

There are a couple of open issues to get proper HA support.  To do this properly, we'll need to modify the kernel web handlers (which currently reside in Jupyter Kernel Gateway) such that a reference to a missing kernel-id will trigger a lookup (and possible reconnect) to the kernel via the persisted sessions, before actually raising a 404 error.  The culling "timers" also require adjustment, etc.

If possible, I would recommend using a single EG instance that spawns kernels using the default behavior or using `KERNEL_NAMESPACE` and I wouldn't expect resource issues.  The EG footprint is generally small when compared to kernel pod/namespaces.

I hope that helps.

**Comment by michzimny** [comment]
Thank you for your reply. 

> Otherwise, by default, EG will create a namespace of the name <kernel-username>-<kernel_id> 

Yes, this is my approach.

I'd like to clarify that I'm considering this now not for having HA but I want them to be totally separated instances, and only living within the same k8s cluster. 

My use case is that one will be a test instance and the another one will be a production instance. This is why using a single EG instance is not an option for me as I'd like to play with the test instance in the same time when my users work in the production one.

How the session persistence can be managed in the k8s deployment? Is it supported? Sorry if you already answered that but I'm not sure I understand it properly. 

I have not configured any session persistence in EG, so this is probably why I'm experiencing orphaned kernel pods in a single EG instance, when restarting EG pod, right?

**Comment by kevin-bates** [comment]
Ah, ok.  I think you should be able to configure a second EG instance in a separate namespace by setting `EG_NAMESPACE` to the appropriate value.  As a result, one instance (and the kernels it launches) will be in the default namespace of `enterprise-gateway`, while the second will be in a different namespace.  Not sure we've tried that concurrently, but it should work.

Regarding the shutdown of the EG pod and its orphaning of kernel pods, it sounds like we need to 'hook' the k8s stop to trigger a `SIGTERM` (which I thought was what happens by default - I might be thinking about docker here).  This _should_ result in the server's attempt to stop all running kernels.  Given that isn't happening, leaves me wondering if there's something else we need to do.

**Comment by michzimny** [comment]
> one instance (and the kernels it launches) will be in the default namespace

I'm not using `EG_SHARED_NAMESPACE`, so the kernels are in separate namespaces, i.e. other than `EG_NAMESPACE`. The same for the second instance.

For me, the shutdown of the EG pod orhpans kernel pods in 100% cases. Shall I create a separate issue for that?

I'm now thinking of a workaround to be able to clean up the cluster after the shutdown of the EG. Having multiple kernel namespaces living in the cluster, is there any way to iterate them and somehow check whether they are orphaned or not? Trying to talk to `EG_RESPONSE_ADDRESS` or sth?

**Comment by kevin-bates** [comment]
Ok, just to clarify on the two EG instances.  Are you setting EG_NAMESPACE to two separate values - one for each instance?  This isn't going to affect the namespaces the kernels run in, but will isolate each EG instance in its own namespace.

Yes, I reproduced the orphaned kernel issue.  We typically don't shutdown EG - at least until all kernels have been shutdown themselves.  To "shutdown" EG in k8s, what are you doing?  Are you stopping the service? deleting the deployment?  When I reproduced the issue, I deleted the service. 

Please open an issue regarding the orphaned kernel pods.  We can discuss things in more detail there.  I believe there's a way to intercept shutdown/deletes in which case we can then trigger the EG shutdown sequence.  I'll try to take a closer look as well.

**Comment by kevin-bates** [comment]
Ok. I've tried spending a bit more time with this tonight.  Actually, deleting the service is not sufficient since I can just restart the service and the kernel is still usable.  However, when I delete the EG pod, another is started, but it doesn't know about the running kernel(s) - which makes sense.  I think we could address this by enabling kernel session persistence, but first, we should understand why the appropriate shutdown protocol is not evident in the pod.  According to the docs, [`SIGTERM` should be sent to the EG during the 30 second grace period](https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods) when deleting the pod and [EG's built-in signal handler should cycle through and attempt to shutdown the kernels](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/enterprisegatewayapp.py#L293).

**Comment by michzimny** [comment]
> Are you setting EG_NAMESPACE to two separate values - one for each instance? This isn't going to affect the namespaces the kernels run in, but will isolate each EG instance in its own namespace.

Yes, this is what I do.

I think this is it for the subject of this thread. Thank you for clarifying.

For the orphaned kernel, I just opened #672.
