### ISSUE TITLE
Launching ipython kernel with custom arguments

### ISSUE THREAD

**Issue by IMAM9AIS** [jupyter/enterprise_gateway#678]
Hi,

I am working on a usecase to integrate an extension with jupyter notebook. This extension has all the three parts to it, the notebook, notebook server and ipython kernel.
Since using JEG, kernels are being launched remotely, we are unable to auto load this extension which requires a change in **ipython_kernel_config.py** in the kernel side. 

This page documents loading of extensions via command line too during kernel launch -  
https://ipython.readthedocs.io/en/stable/config/options/terminal.html

I tried passing --ext=extension_name in LAUNCH_OPTS part in kernel.json file of my kernel but it resulted in a failing job.

can you please tell me, if changing LAUNCH_OPTS is the right way to pass an option during ipython kernel launch. Also if i have a remote ipython_kernel_config.py in my profile can this profile be used in way to launch the kernels so that i can tweek this file locally before launch ?

Thanks,
Imam

**Comment by kevin-bates** [comment]
Hmm.  We haven't dealt with this kind of thing before.  Yes, I would have expected that `LAUNCH_OPTS` would have ultimately conveyed the option to the ipykernel that is embedded in the kernel launcher code.  What is the nature of your failure?

Because the kernel is not invoked locally, I don't think its config file will come into play.  In addition, since it can't be determined where the kernel will ultimately run within the cluster (outside of containerized envs), I suspect the configuration file would need to be conveyed during the launch.

Can you describe your environment?  Are these containerized envs?  Are you using YARN and/or Spark?

What kinds of things does your `--ext` provide to the kernel?  

I suspect we'll need to _extend_ our launch mechanism to support this (pun intended) and would be happy to guide you down that path.

**Comment by kevin-bates** [comment]
@IMAM9AIS - have you had any progress on this or can you provide more information?  Thanks.

**Comment by kevin-bates** [comment]
Closing due to lack of information.  Please re-open if you feel that is warranted.
