### ISSUE TITLE
Request to Kernel spawn fails even if the KG_REQUEST_TIMEOUT and KG_CONNECT_TIMEOUT are increased

### ISSUE THREAD

**Issue by suryag10** [jupyter/enterprise_gateway#683]
Hi,
I am using nb2kg 0.6.0 k8s to spawn the kernels. At the EG side it is taking more than 200 seconds to download the docker image and start the kernel(KERNEL LAUNCH TIMEOUT increaed to 300). EG is able to spawn the kernel, but the request at nb2kg is failing at 60 seconds as shows in attachments and a seconds request is sent to spawn the new kernel. i had tried to increase KG_REQUEST_TIMEOUT and KG_CONNECT_TIMEOUT to 300 seconds even. But the behaviour is same. EG version used in 2.0.0.rc1. the result is kernel spawned is remaining in dangling state and is not being culled as well. Pls let me know.

![Capture1](https://user-images.githubusercontent.com/42367117/59374452-7ffed380-8d69-11e9-843e-0b1a24204595.PNG)
![Capture2](https://user-images.githubusercontent.com/42367117/59374454-80976a00-8d69-11e9-8f5f-6b7c6c4adce2.PNG)

**Comment by kevin-bates** [comment]
@suryag10 - I felt this issue was more appropriate in EG at the moment.  Thank you for bringing it up.

I think you might be getting bit by yet a third time-based variable `KERNEL_LAUNCH_TIMEOUT` which defaults to `60` seconds via the `EG_KERNEL_LAUNCH_TIMEOUT` value that is used if the request doesn't provide `KERNEL_LAUNCH_TIMEOUT`.  You should probably increase that value (in the yaml file) as well.

We recommend in our docs pre-populating your kernel images prior to launch.  One larger clusters, we know this can be an issue, however, it avoids initial pull issues on each node for each kernel image.

One of the things in master (we owe people a 2nd rc release!) is a [kernel-image-puller](https://github.com/jupyter/enterprise_gateway/tree/master/etc/docker/kernel-image-puller) that is configured using [helm charts](https://github.com/jupyter/enterprise_gateway/tree/master/etc/kubernetes/helm/enterprise-gateway) as a daemonset.  This periodically pulls the available kernelspec files and extracts the image names from each and ensures those images are up to date on each node of the cluster.

This would alleviate having to set the various TIMEOUT values to exceedingly large values that will otherwise affect getting failure statuses back in a more timely manner.

**Comment by kevin-bates** [comment]
Sorry - I just re-read the OP and see you had already increased the launch timeout.  Was that value set on the client side, or server?

**Comment by suryag10** [comment]
Hi Kevin,
Thx for the update. KERNEL_LAUNCH_TIMEOUT and EG_KERNEL_LAUNCH_TIMEOUT  are available both at NB2KG as well as EG. This has been increased to 300 seconds.

**Comment by kevin-bates** [comment]
Hi Suryanarayana, have you been able to confirm if kernels run fine after their initial image pull?  Rather than artificially increasing the limits to account for pull times, I think its best to configure the kernel-image-puller.  Then, once the EG deployment starts, let the image pullers do their thing and, shortly, all nodes will be populated with kernel images.

**Comment by suryag10** [comment]
Hi Kevin,
If the image pull happens within 60 seconds, then there is no issue. Kernels run fine and they are able to perform the tasks as well. Issue is seen only when the image pull takes more than 60 seconds. There is no link between the kernel spawned and nb2kg interface after the timeout.

**Comment by suryag10** [comment]
One quick question here, are there any other timeout's which are defaulted to 60 seconds in NB2KG or EG in the kernel bringup flow.

**Comment by kevin-bates** [comment]
Not that I'm aware.  However, we should try to make sure the server is getting the KERNEL_ values appropriately.  Can you provide the EG log prior to and including the failed startups?  If you don't enable DEBUG, please do so prior to the capture.  Then zip and attach. Thanks.

One thing you can also do for confirmation is modify the kernel pod yaml (or jinja template if that's what you're using) to 'flow' KERNEL_LAUNCH_TIMEOUT, then print the env from a running kernel successfully spawned in this fashion.  

(This reminds me that we need to automatically flow *all* KERNEL_ variables to the containerized kernels!)

**Comment by suryag10** [comment]
Hi Kevin,
Will upload the logs today as i was busy with other Critical Work.

**Comment by esevan** [comment]
I've experienced same issue, and the issue was raised by the Proxy configuration such as nginx, and HAProxy in front of EG. Please check the timeout configuration if you have any.

I hope it's the case :)

**Comment by kevin-bates** [comment]
Great point regarding a proxy @esevan - thanks!

**Comment by suryag10** [comment]
hi esevan,
i had tried to set the following values:
    ingress.kubernetes.io/proxy-connect-timeout: "600"
    ingress.kubernetes.io/proxy-read-timeout: "600"
    ingress.kubernetes.io/proxy-send-timeout: "600"
    ingress.kubernetes.io/send-timeout: "600"

Still its the Same. We have nginx in front of the proxy and nb2kg directly contacts the EG.

**Comment by suryag10** [comment]
Hi kevin,
Following are the logs as requested. 

[eg_logs_timeout_kernel_spawn.txt](https://github.com/jupyter/enterprise_gateway/files/3317155/eg_logs_timeout_kernel_spawn.txt)

pls let me know, if u need more info.

**Comment by kevin-bates** [comment]
Hi @suryag10 - thank you for the logs.  You definitely have KERNEL_LAUNCH_TIMEOUT set (to 300) and there's really no timeout occurring within EG at all.  Here's what I see.

The kernel is taking 65 seconds to start.  Here are the interesting entries.

1. 18:25:18. Start request processing starts.
2. 18:25:30. Status changes from None to Pending and driver pod is "running".
3. 18:26:15. Status changes from Pending to Running in driver pod.
4. 18:26:18. Connection information received.
5. 18:26:18. Kernel started.
6. 18:26:23. Kernel-info requested.
7. 18:26:23. Kernel-info received.

I suspect the image is being pulled between steps 2 and 3 for a 45 second "penalty".

What exactly do you see in the client-side (NB2KG) logs?  Above I see a 504 response.  I would have expected 503 (timeout).

Is there anyway you can confirm what value of `KG_REQUEST_TIMEOUT` is getting used within NB2KG?  If the exception is occurring at exactly the 60 second mark, then I suspect your custom value is not getting used.  Since this isn't a "server side" value, the EG log won't show what's happening.

While I agree this it would be good to understand this, you should really pre-seed your cluster with the appropriate kernel images.  We have provided the `kernel-image-puller` exactly for that purpose.

I am happy to continue troubleshooting this issue in lieu of pre-populating your kernel images.   This process may take some time.

A couple of things.
1. Not that it will change the results, but it might provide different information - could you try using the /tree endpoint (i.e., Notebook classic) rather than /lab?
2. Do you see this same behavior using the "vanilla" python kernel?  This will remove Spark from the equation.  Again, if image pull time is the culprit, it probably won't change the results, but it may provide different information.

On the bright side, the server is behaving exactly as it should. :-)

Thanks for your patience.

**Comment by suryag10** [comment]
> Hi @suryag10 - thank you for the logs. You definitely have KERNEL_LAUNCH_TIMEOUT set (to 300) and there's really no timeout occurring within EG at all.
[Surya] hi Kevin, Yes absolutely, there is no issue in EG at all if you observe my original first post. The issue is happening at nb2kg end where it bails out and displays the error as attached. 
 
Here's what I see.
> 
> The kernel is taking 65 seconds to start. 
[Surya] We are trying to optimize the kernel docker image size and thats the reason it has come down to 65 seconds. 

Here are the interesting entries.
> 
> 1. 18:25:18. Start request processing starts.
> 2. 18:25:30. Status changes from None to Pending and driver pod is "running".
> 3. 18:26:15. Status changes from Pending to Running in driver pod.
> 4. 18:26:18. Connection information received.
> 5. 18:26:18. Kernel started.
> 6. 18:26:23. Kernel-info requested.
> 7. 18:26:23. Kernel-info received.
> 
> I suspect the image is being pulled between steps 2 and 3 for a 45 second "penalty".
> 
> What exactly do you see in the client-side (NB2KG) logs? Above I see a 504 response. I would have expected 503 (timeout).
[Surya] Will provide you the logs at nb2kg. 
> 
> Is there anyway you can confirm what value of `KG_REQUEST_TIMEOUT` is getting used within NB2KG? If the exception is occurring at exactly the 60 second mark, then I suspect your custom value is not getting used. Since this isn't a "server side" value, the EG log won't show what's happening.
[Surya] Sure. Will provide you the logs at nb2kg and will try to add some logs as well. 
> 
> While I agree this it would be good to understand this, you should really pre-seed your cluster with the appropriate kernel images. We have provided the `kernel-image-puller` exactly for that purpose.
> 
> I am happy to continue troubleshooting this issue in lieu of pre-populating your kernel images. This process may take some time.
> 
> A couple of things.
> 
> 1. Not that it will change the results, but it might provide different information - could you try using the /tree endpoint (i.e., Notebook classic) rather than /lab?
[Surya] Sure. 
> 2. Do you see this same behavior using the "vanilla" python kernel?  This will remove Spark from the equation.  Again, if image pull time is the culprit, it probably won't change the results, but it may provide different information.
[Surya] Yes the issue started popping from the initial python kernel  itself and are seeing the issue with all kernels. Yes, what i also feel is that the image pull time is the culprit. when image is being pulled within 60 seconds, there is no issue observed. 
> 
> On the bright side, the server is behaving exactly as it should. :-)
[Surya] yes, EG is perfect, but the issue is the kernel pods which are spawned earlier due to the failed requests at NB2KG are not being cleaned as well even after the cull timeout. We might need to check for this cleanup as well. 
> 
> Thanks for your patience.

**Comment by kevin-bates** [comment]
>The kernel is taking 65 seconds to start.
[Surya] We are trying to optimize the kernel docker image size and thats the reason it has come down to 65 seconds.

This is a one-time thing.  I don't understand why you're not using kernel-image-puller?  Even if you trim the image size, there's nothing to say an _extended_ image won't then break the timeout values?  In addition, you're now imposing super long delays on real issues because KERNEL_LAUNCH_TIMEOUT is so high.  With this, if there's some "valid" reason why the image doesn't load (say, due to some configuration issue), EG will not convey the issue until the timeout has been exhausted.

I just want to be sure we haven't missed some design point with kernel-image-puller.  This is the precise issue for which it exists.

**Comment by suryag10** [comment]
> > The kernel is taking 65 seconds to start.
> > [Surya] We are trying to optimize the kernel docker image size and thats the reason it has come down to 65 seconds.
> 
> This is a one-time thing. I don't understand why you're not using kernel-image-puller? Even if you trim the image size, there's nothing to say an _extended_ image won't then break the timeout values? In addition, you're now imposing super long delays on real issues because KERNEL_LAUNCH_TIMEOUT is so high. With this, if there's some "valid" reason why the image doesn't load (say, due to some configuration issue), EG will not convey the issue until the timeout has been exhausted.
> 
> I just want to be sure we haven't missed some design point with kernel-image-puller. This is the precise issue for which it exists.
[Surya] We have limitations with respect to the resources which are being used by the kernel-image-puller such as the daemonset and host mount for docker. Atleast from a design perspective, i feel that the nb2kg should honor the KG_REQUEST_TIMEOUT and KG_CONNECT_TIMEOUT which at present seems missing. Will try to debug more and provide the logs.

**Comment by suryag10** [comment]
One more point to note, even if the kernel image puller is taken there is a chance that the timeout can happen still in the following case:
Consider the case of kernel image size is high, say some 4 to 5GB. If the image pull takes more time, then its the same case as mentioned above as well. I feel at nb2kg also this timeouts need to be considered. Pls let me know your thoughts as well.

**Comment by kevin-bates** [comment]
I'm not sure I'm following your last point.  Daemonset and docker.sock mount aside, the idea is that EG "warmup" prior to user interaction.  This takes a couple minutes on the initial deployment.  Once each node has pulled the kernel images ONCE, they are available for usage.  4-5GB images will not be out of the ordinary.  Those images should not (can not) be pulled during user kernel startup requests for each node on which that kernel image has not run.  If a daemonset and/or docker.sock mount aren't acceptable, then I would strongly recommend a script be written to pre-populate a node.

That said, I completely agree that we should be able to tolerate launch times greater than 60 seconds - if nothing more than to handle this kind of scenario.  Since we know the server is working fine and `KERNEL_LAUNCH_TIMEOUT` is being honored, we must look into the client (nb2kg) side (as you have previously pointed out and correctly originated this issue against).  

I recently released NB2KG 0.7.0.  One of the changes there is to ensure `KG_REQUEST_TIMEOUT` is at least as large as `KERNEL_LAUNCH_TIMEOUT` plus a pad (default of 2 seconds).  Have you tried using that version?  If so, you might try NOT setting `KG_REQUEST_TIMEOUT` at all and let its value be driven by `KERNEL_LAUNCH_TIMEOUT`.

If this doesn't prove useful, then you may need to instrument NB2KG to ensure that `HTTPClient` is starting with a `request_timeout` keyword argument of the expected value.  If that all looks correct, then its probably a matter of more digging.  Thanks.

**Comment by kevin-bates** [comment]
I'm going to close this issue as it seems fairly stale and lots have changed since.  Please re-open if you feel that's an issue.
