### ISSUE TITLE
SparkYarn Kernels Do not pick up RM HTTPS URL correctly

### ISSUE THREAD

**Issue by chuyqa** [jupyter/enterprise_gateway#729]
## Description

In a Kerberos + SSL Enabled Resource Manager, `--EnterpriseGatewayApp_yarn_endpoint=` does not correctly get picked up for all calls - specicially the http:// and port scheme. 

## Screenshots / Logs

1. The correct URL is used for launching the kernel:
```
[D 2019-09-05 10:42:14.992 EnterpriseGatewayApp] Yarn cluster kernel launched using 
YARN endpoint: https://huron-master.test:8090/ws/v1/cluster, 
pid: 21316, Kernel ID: b84f7c33-4913-41eb-8a0a-6d3237ac9f6b, cmd: '['/opt/ibm/dsxhi/jeg/kernelspecs/spark_python_yarn_cluster/bin/run.sh', '--RemoteProcessProxy.kernel-id', 'b84f7c33-4913-41eb-8a0a-6d3237ac9f6b', '--RemoteProcessProxy.response-address', '172.16.244.84:60168', '--RemoteProcessProxy.port-range', '0..0', '--RemoteProcessProxy.spark-context-initialization-mode', 'lazy']'

Starting IPython kernel for Spark in Yarn Cluster mode as user user1
```
2. A 500 is immediately returned, as the Query for that kernel is checking the RM http port, 8088.. and not the https 8090:
```
[W 2019-09-05 10:42:15.519 EnterpriseGatewayApp] Query for kernel ID 'b84f7c33-4913-41eb-8a0a-6d3237ac9f6b'
 failed with exception: <class 'requests.exceptions.ConnectionError'> - 
'HTTPConnectionPool(host='huron-master.test.com', port=8088): Max retries exceeded with url: /ws/v1/cluster/apps?startedTimeBegin=1567705334000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f03386ef5f8>: Failed to establish a new connection: [Errno 111] Connection refused',))'.  Continuing...
```

I believe this could be related into how yarn-site.xml is laid down when HTTPS is enabled. For example on a CDH 6.2 cluster with Auto TLS, note both `webapp.address` and `webapp.https.address` are present, but the Yarn Resource Manager only listens on the https scheme as determined by policy:

```
  <property>
    <name>yarn.resourcemanager.webapp.address</name>
    <value>huron-master.test.com:8088</value>
  </property>
  <property>
    <name>yarn.resourcemanager.webapp.https.address</name>
    <value>huron-master.test.com:8090</value>
  </property>
  <property>
    <name>yarn.http.policy</name>
    <value>HTTPS_ONLY</value>
  </property>
```

## Environment

- Enterprise Gateway Version [2.0.0]
- Platform: CDH 6.2. Kerberos + Auto TLS for Yarn.

**Comment by kevin-bates** [comment]
Hello @chuyqa - thanks for opening this - it's definitely an issue.  Here's my assessment...

1. It looks like you're using builds relative to 2.0.0rc1 (or older).  The reason I say this is because the log message in item 1 displays the full endpoint value.  In rc2 and, as of yesterday - the GA release, this log statement will not display the scheme[*] and composes the ["RM address"](https://github.com/jupyter/enterprise_gateway/blob/v2.0.0/enterprise_gateway/services/processproxies/yarn.py#L54-L71) value from the hostname and port.
2. The yarn-api-client packaged used by EG does not support the https scheme (well, it essentially ignores it): https://github.com/toidi/hadoop-yarn-api-python-client/blob/master/yarn_api_client/base.py#L28-L29
and the ResourceManager initializer doesn't (currently) take a scheme: https://github.com/toidi/hadoop-yarn-api-python-client/blob/master/yarn_api_client/resource_manager.py#L10-L40
3. Another strange thing is that between the two log statements, the port changes from 8090 to 8088.  However, I believe that's probably because it tries **http**://...:8090 - which doesn't work, then falls back to using the address from the `yarn-site.xml` file.
4. There's an open PR that I believe we can probably merge, but changes the YARN-api-client API.  This [PR](https://github.com/toidi/hadoop-yarn-api-python-client/pull/34) takes the complete endpoint (i.e., includes scheme).  One of the primary goals of this PR is to support https.
5. Since rc1, we've made changes that allow for users NOT specifying an endpoint via JEG, in which case, yarn-api-client defers to the `yarn-site.xml` file.  However, that deferral does not honor any potential policy, pulling only [yarn.resourcemanager.webapp.address](https://github.com/toidi/hadoop-yarn-api-python-client/blob/master/yarn_api_client/hadoop_conf.py#L22-L32)

Here are some approaches we could take - short-term, long-term.

Short-term:
Fix the current version of yarn-api-client to honor the policy in `yarn-site.xml`.  This will likely mean introducing the scheme's value as an instance variable (`self.scheme`).
Assuming that works - use EG 2.0 GA and NOT set the endpoint option.  This will lead yarn-api-client to hit the `yarn-site.xml`.

Long-term:
Merge the code-cleanup PR in yarn-api-client.  We will need to make sure that the http policy is also honored (so this should include most of the short-term fix - although that should only come into play when no endpoint is provided).
Update JEG to use the new API provided by the PR's merge.

[*] The fix for this should be sure to display the endpoint's scheme if provided (applies to the 'Long-term' approach).

I'd be happy to provide you with a yarn-api-client that honors the http policy and pulls the correct address accordingly in order to see how the Short-term approach goes.

**Comment by chuyqa** [comment]
>  2.0.0rc1

That's correct - this was 2.0.0.rc1 - Thanks for pointing out that 2.0.0 got GA'd! will update to 2.0.0 GA bits asap. 

Makes sense regarding Short/Long term approaches.. 
For the Short-term fix, that would be fantastic if you have some ideas on patching yarn-api-client

**Comment by kevin-bates** [comment]
@chuyqa - I have posted a possible interim change (and POC) to this branch: https://github.com/kevin-bates/hadoop-yarn-api-python-client/tree/honor-http-policy 

and attached a corresponding whl file (rename .zip to .whl)

[yarn_api_client-0.3.7.dev0-py2.py3-none-any.zip](https://github.com/jupyter/enterprise_gateway/files/3581574/yarn_api_client-0.3.7.dev0-py2.py3-none-any.zip)

In order to test this change, you'll need to UNSET the yarn-endpoint configuration value, otherwise yarn-api client will assume everything is http.

I have tested this change for the HTTP_ONLY policy.  I have also changed my configuration's policy to HTTPS_ONLY to confirm the parsing logic works and the appropriate endpoint is constructed.  However, I get the following failure - presumably because I don't have SSL configured, etc:
```
      File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='yarn-eg-node-1.fyre.ibm.com', port=8090): Max retries exceeded with url: /ws/v1/cluster/scheduler (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc3edfc7e48>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

I would also recommend you set the following env variable to be included in EG's env at startup: `EG_YARN_LOG_LEVEL=INFO`.  Because yarn-api-client can be verbose (and produce messages for every poll interval) we normally set its logging level to `WARNING` by default.  Once set, and a kernel has been launched, you should see entries similar to the following:
```
[I 190905 16:26:48 base:33] API Endpoint https://yarn-eg-node-1.fyre.ibm.com:8090/ws/v1/cluster/scheduler
```

I suspect this may require some iterations, so please feel free to apply changes to the branch or your local copy.

Thanks for your help.

**Comment by chuyqa** [comment]
Thanks for the whl - was able to verify correct RM URLs are picked up now - 

> 'HTTPSConnectionPool(host='huron-master.test.com', port=8090): Max retries exceeded with url: /ws/v1/cluster/apps?startedTimeBegin=1567810857000 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]

The latter issue is now related to the dispatch from JEG -> ResourceManager. This should work on a ca-issued cert (or FreeIPA) with `update-ca-trust` being ran.. Will give it a shot on a different cluster

I see the Code Cleanup PR adds in a `verify` with a path to the ca bundle .pem, which looks promising.. Will see how I can help validate/test on my ssl clusters
https://github.com/toidi/hadoop-yarn-api-python-client/pull/34

**Comment by kevin-bates** [comment]
Created PR https://github.com/toidi/hadoop-yarn-api-python-client/pull/41 which enables the ability to honor the configured http policy in yarn-site.xml.  Use of this PR requires that **no YARN endpoint be set!**
