### ISSUE TITLE
Skaffold for Kernel Images

### ISSUE THREAD

**Issue by simisoz** [jupyter/enterprise_gateway#746]
Why can't we use Skaffold to build the kernel images in a separate project? 
https://github.com/GoogleContainerTools/skaffold.

**Comment by kevin-bates** [comment]
Hi @simisoz - thanks for the issue.  This is the first I've heard about Skaffold - not sure if others in the community are familiar with it or not.  At any rate, you provide very little additional information for me to help you, so please answer the following questions...

1. What is the nature of the problem preventing you from "building kernel images in a separate project"?
2. Are you extending an [existing kernel image](https://hub.docker.com/u/elyra/) or attempting to build one from scratch?

Unfortunately, our images require additional modules for wrapping the kernel, so unless you're extending an existing image, I suspect you might run into issues.  Please provide answers to the above questions and make sure you've read the docs regarding [custom images](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/docker.html#custom-kernel-images).  Thanks.

**Comment by kevin-bates** [comment]
Looking at the skaffold stuff, I'm not sure how good a fit EG would be here since we currently have many external dependencies that, I think, would make this diffcult.

@simisoz - have you had a chance to look into this further?  If not, I think we should close this issue.  It can be reopened should this need to be revisited.
