### ISSUE TITLE
Configuring the request queue size in JEG 

### ISSUE THREAD

**Issue by amangarg96** [jupyter/enterprise_gateway#757]
Feature Request for configuring the request queue size in JEG

## Description

Due to the following [issue](https://github.com/jupyter/enterprise_gateway/issues/86), all subsequent requests are queued at JEG during Kernel Launch. 
In case of Spark kernels, kernel startup can take more than 10-15 seconds. If two users are using the same JEG instance, and if one user has launched a kernel, the other user's requests (which might not be a kernel launch request) are queued for that duration.
Gateway timeouts (generally set in the order of minutes) acts as a guardrail for not making the user wait indefinitely, but waiting for timeouts and eventually not getting a response from JEG still leads to a bad user experience.

I suggest a request queue size configuration is set at JEG level which takes in the number of requests (n) that can be queued at JEG. If (n+1)th request is received, it should be rejected and sent back with a proper Error message. (`HTTP 5XX: Gateway is busy executing other requests`).

## Environment

- Enterprise Gateway Version 1.2.0
- Platform: YARN

**Comment by kevin-bates** [comment]
Thanks for opening the issue.  I believe most all of this will be addressed once asynchronous support is available.  In the meantime, you might want to utilize the feature added in #699.  That PR was implemented to check YARN's queue as part of the synchronous launch, so that may be helpful in that no kernels should be started if YARN doesn't have the resources.  This should reduce some contention - although I agree does not resolve the issue.

Regarding timeframes.  The jupyter_server project should be leveraging asynchronous kernels using [kernel providers](https://github.com/takluyver/jupyter_kernel_mgmt).  In that configuration, EG would be a server extension and the remote kernels would be provisioned as providers.   That's still a ways off, but might have better odds of "public exposure" sooner than having async startup in the notebook server stack (unfortunately). 

Were you planning on implementing a request queue mechanism?  It sounds like something that would be generally useful.

**Comment by amangarg96** [comment]
Implementing EG as a server extension and ditching the notebook server stack certainly feels like a faster way to reach the goal of async kernels 😄 
Once kernels are async and EG is HA, it would solve most of the issues (atleast for my setup).

Yes, I was thinking of having a request queue mechanism at EG level but would need some pointers to understand how all the requests are queued at JEG currently, and which component needs to be tweaked for it (I'm guessing it would be at the tornado level).

Sorry for the delayed response :)

**Comment by kevin-bates** [comment]
There is no explicit request queueing that happens today.  I suppose, at some level (probably tornado), web requests are "queued" waiting for a time-slice, but since everything is synchronous, they get backed up.  I'm not really sure how this would be exposed or controlled.

You might also be able to alleviate some issues by starting multiple EG instances and fronting them with a load balancer.  The requirement there is that sticky sessions be used so that a kernel's lifecycle remain on the same EG instance.

**Comment by kevin-bates** [comment]
Async kernel managers are built into the jupyter stack.  As a result, I'm closing this issue.  Feel free to re-open if this closure wasn't warranted.
