### ISSUE TITLE
Run notebooks in docker containers in distributed mode

### ISSUE THREAD

**Issue by golf-player** [jupyter/enterprise_gateway#758]
How possible would it be to do this? 

I think the difficulty here is making a processproxy that does similar things to the ssh one and the docker one and also passing which docker image to run a notebook in. 

Is this something you would be interested in having a pull request if I get the time to implement it? Can you see any pitfalls, or reason this doesn't already exist?

**Comment by kevin-bates** [comment]
How is this different from what JupyterHub does?  It essentially launches notebook _servers_ in pods (k8s).  Does it not have docker swarm support?

If you're talking about just running a kernel (that operates on behalf of a notebook), then we already support this via [`DockerSwarmProcessProxy`](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/docker_swarm.py#L21).  Each of the container-based process proxies (k8s and docker*) support an image field in their respective kernelspec files.

Could you please clarify what you're looking for?  Should there be a need to add additional functionality and it makes sense that it reside in EG, then, by all means, we'd love a PR.  But let's see if that's necessary first.  Thanks.

**Comment by golf-player** [comment]
Is it possible to use dockerswarmprocessproxy without actually having a
docker swarm cluster? It was my impression that it was not.

My objective here is to spin up a kernel inside a docker container, but
that doesn't appear to be something EG supports outside of kubernetes pp
and dockerswarm pp.

Please correct me if I'm wrong?

This DistributedDockerProcessProxy would do the exact same thing as
Distributed process proxy, except the command would be `docker run
whatever` (and the other changes necessary for processproxy like kernel
info and status)

**Comment by kevin-bates** [comment]
I see.  Hmm.  I'm really hesitant to introduce a third flavor of docker, especially for a use case that Docker Swarm addresses completely (IMHO).  The `docker run whatever` command, does it take a remote host as a value.  Currently the DistributedProcessProxy uses ssh to essentially remote the under-lying command and there a lots of pitfalls with that configuration (it was primarily a proof of concept thing).  I suspect you'd be doing the same thing, where the target of remote shell invocation is `docker run whatever` on the remote host.

What is the hesitancy to use a docker swarm cluster?  Just curious what that doesn't solve for you.

I think you may encounter load issues with a distributed approach that resource managers like docker swarm and k8s are meant to address.  That said, you can also extend the host selection method.  (We'd love to make that pluggable as well, but the need hasn't been there yet.)

**Comment by golf-player** [comment]
Interesting. I was not aware of distributed processproxy being a proof of
concept thing. Is the plan to eventually ditch it and only maintain the
kubernetes, yarn, swarm, etc proxies in the main repo? Or maybe ssh could
be replaced with something like kafka or even just rpc?

The only reason I don't use swarm or kube is that it's easier to use
existing boxes/kube pods than it is to get permission to run arbitrary kube
pods or spin up my own cluster. Procurement issues basically.

Load issues are definitely a concern and something I've run into in the
past with an rmq based approach to remote kernels.

I'm also somewhat hesitant to add a new proxy given what I'm reading now
about eg having an architecture change to providers potentially in the
future.

Apparently docker 18.09 does have the capacity to run things on a remote
host. So maybe this could just be a subclass from the docker processproxy
that mixes in a few concepts from distributed processproxy

**Comment by kevin-bates** [comment]
We fully support DistributedProcessProxy, but it just hasn't had the "airtime" and focus that YarnClusterPP and K8sPP have had.  We're not planning on ditching it, although I think a kafka approach would be really interesting!

I understand the procurement issues and we probably overlook those kinds of concerns given we're trying to focus on enterprise-scale areas.  

Regarding kernel providers, you're right, there will be some changes assuming the kernel provider approach is adopted by the new jupyter_server (which is likely).  However, process proxies built on RemoteProcessProxy can be converted to a kernel provider derived from [`RemoteKernelProvider`](https://github.com/gateway-experiments/remote_kernel_provider) quite easily.  (Note, the repos under gateway-experiments are absolutely POC entities. :smile:) . As a result, I don't think that should preclude you of pursuing a process-proxy-based solution now.  We would be happy to work with you to  migrate your PP solution to a KP solution.

I think it would be worthwhile looking into the docker 18.09 remote host stuff.  This could very likely be something that could be parameterized in the compose yaml file and no additional PP would be necessary.  I would make that a focus first.

Please keep in touch on things.  We are happy to jump into a virtual meeting or collaborate otherwise.  Please don't hesitate to reach out.

**Comment by golf-player** [comment]
Without going too deeply into it, we need Enterprise scale without
Enterprise funding, and I feel this is a decent approach to achieve that,
given that a similar approach has worked for a while but is now very behind
what modern jupyter's capable of.

Really appreciate the information. I'll let you know how things go. I'll be
working on a PoC tomorrow for the docker idea.

**Comment by golf-player** [comment]
Forgot I had this open...

Closing this since I it was a bad idea to begin with
