### ISSUE TITLE
Mixing Local and remote kernel

### ISSUE THREAD

**Issue by georghildebrand** [jupyter/enterprise_gateway#789]
Just a general question. How difficult would it be to have local and remote kernels in the notebook server available?

**Comment by lresende** [comment]
JEG supports both relatively to JEG environment, which means, Notebook will connect to JEG, and JEG can create local and remote/distributed kernels. You can accomplish this by not specifying a  `metadata.process_proxy.class_name` in the kernel.json.

Does that answer your question?

**Comment by snu-ceyda** [comment]
I haven't thoroughly tested it but it can result in some security issues (especially on multi-user settings using Jupyterhub) The senario is as below;
1 - Gateway is run as root 
2 - Gateway finds a simple python kernel in "/home/[user]/.local/share/jupyter/kernels/python3"
3 - User requests that kernel 
4 - Gateway uses `LocalProcessProxy` to launch the kernel (which just checks against `unauthorized_users` ) 
5 - The user is now root inside the notebook! Assuming the user is authorized we still wouldn't want to be root...which also messes the python packages environment etc
`KERNEL_USER` variable is still set but `LocalProcessProxy `does nothing to launch using the correct user (as far as I can see)?

**Comment by kevin-bates** [comment]
Yes, that can be an issue with EG and local kernels - its design center is around managed clusters. 

Is there a reason you're running Gateway as root?

**Comment by snu-ceyda** [comment]
> Is there a reason you're running Gateway as root?

yes, because I'm doing container stuff (creation, launch etc)

But even if it wasn't root and some unprivileged user it would still be a problem since all users's notebooks would end up using the same user's configuration (dangerous if they do "!pip install something" in the notebooks etc)

BTW, LocalProcessProxy also ignores `KERNEL_WORKING_DIR` too. There is a simple enough fix I'm using now.  I can do a PR if it is okay to treat `KERNEL_WORKING_DIR` as an non container [configuration ](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/config-options.html#per-kernel-environment-overrides) variable.

**Comment by kevin-bates** [comment]
> But even if it wasn't root and some unprivileged user it would still be a problem since all users's notebooks would end up using the same user's configuration (dangerous if they do "!pip install something" in the notebooks etc)

Yes, this is known behavior and why we recommend using impersonation and remote kernels (for their isolation).

> BTW, LocalProcessProxy also ignores KERNEL_WORKING_DIR too. There is a simple enough fix I'm using now. I can do a PR if it is okay to treat KERNEL_WORKING_DIR as an non container configuration variable.

I guess I'm not surprised since local kernels aren't a focus but purely for backward compatibility with Jupyter Kernel Gateway - where these behaviors exist.  Yes, please submit a PR  - thank you!

**Comment by georghildebrand** [comment]
I tested and it works as @lresende described. The security concerns should be covered separately.
