### ISSUE TITLE
Race condition with EG_MAX_KERNELS

### ISSUE THREAD

**Issue by zrlkau** [jupyter/enterprise_gateway#855]
Hi,

I'm trying to limit the number of kernels a client can start. I've tried setting EG_MAX_KERNELS, EG_MAX_KERNELS_PER_USER and their corresponding command line options. Unfortunately, if the client starts kernels quickly, it can get around this issue and leave me with more than double the set limit (8, in my case) due to an apparent race condition where kernels only count towards the limit once they're been started successfully. The behaviour that I would expect is that a kernel counts towards the limit as soon as the client requests its start. Only if it fails to start after a certain time-out it is removed from that limit again and another kernel can be started. I'm using JEG 2.2.0rc2 with asynchronous kernel starts.

Thanks,
Michael

**Comment by kevin-bates** [comment]
Thanks Michael.  Correct, this is one of the _negative_ impacts of async kernel starts.  The problem is that we will need to have a parallel mechanism that tracks kernels such that _pending_ starts are counted as if they are started (which seems a bit counterintuitive to me).  Another issue is that we don't necessarily know the kernel's id (used for tracking) until the startup request has completed - not to mention that this area of the software spans two additional packages (notebook and jupyter_client) - although we will only make the change in EG (since its the only layer that includes this functionality).

Did you want to take a stab at addressing this?

**Comment by zrlkau** [comment]
I'm afraid I don't have time at the moment to work on a fix for this issue.

**Comment by kevin-bates** [comment]
Hi @zrlkau - I've been noodling this in my head the last few days, but haven't gotten around to taking a closer look.   It's on my radar and I hope to be able to get around to this in the next few days.  I would definitely like to address this before we cut EG 2.2.0 GA.
