### ISSUE TITLE
Node Affinity Helm Depolyment

### ISSUE THREAD

**Issue by ashvinnihalani** [jupyter/enterprise_gateway#876]
How do I specific node affinity for the kernel pods that are launched with a helm deployment? Looking at the actual deployment it seems I would modify the pod definition in the etc scripts folder however in the helm deployment that file isn't there?

More over how do I change any parameter of how the kernel launches? I would like to change the name as well.

**Comment by kevin-bates** [comment]
Hi @ashvinnihalani,

The helm deployment only addresses the deployment of EG.  Within EG, kernels are launched using the [`kernel-pod.yaml`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml.j2) file located in their respective kernel specification folders.  Within the repository, there is a single copy of the `kernel-pod.yaml` and this copy is distributed across the various kernel specs that are composed during the build.

The `kernel-pod.yaml` is templated and it should be noted that, for the most part, all `{{kernel_xxx}}` correspond to envs of the name `KERNEL_xxx` - which automatically _flow_ from the notebook/lab client.  Since it appears we have a variable for the pod name (`{{kernel_pod_name}}`) you should be able to set that (fixed or variable) value prior to launching the respective client.  I haven't visited this aspect of functionality in a while, but that's the general idea.

As for _node affinity_ that too should be specifiable in the k8s YAML script - and is one reason we give each kernelspec its own copy - since some kernels may need affinity to particular resources over others.  You'll need to reference the k8s docs for how that is specified.

**Comment by ashvinnihalani** [comment]
So to clarify I have to build custom kernel images to specify any of these parameters. The helm deployment includes some basic images such as Python, TF and R, I have to rebuild all of those?

**Comment by ashvinnihalani** [comment]
So by modifying the .yaml file in usr/local/share/jupyter/kernels folder of the running pod I was able to achieve the desired behavior. Now the question is how do I build that into launch. I see a kernelpecs image in the values.yaml file I assume I have to create one of those. Is this a docker image or another type and is there one I can base my modified one off of?

**Comment by ashvinnihalani** [comment]
Okay so it's a docker image where the specs are just copied over to a /kernels folder. However there is a typo in the deployment.yaml file: emptydir should be emptyDir. I'll create a pull request when I get off work. 

Side note: perhaps the location in the documents on could be moved its in a fairly obscure place for what is a fairly common customization.

**Comment by kevin-bates** [comment]
> So to clarify I have to build custom kernel images to specify any of these parameters. The helm deployment includes some basic images such as Python, TF and R, I have to rebuild all of those?

Those images you reference are kernel pod images.  The kernel-pod.yaml resides in the Enterprise Gateway image - so no modifications to the kernel pod images should be necessary

> I see a kernelpecs image in the values.yaml file I assume I have to create one of those. Is this a docker image or another type and is there one I can base my modified one off of?

Yes, all images are docker images.  This entry was a contribution so we don't have a reference, unfortunately.  If you build one, it would be create if you could update the docs with the appropriate changes/Dockerfile example.

> However there is a typo in the deployment.yaml file: emptydir should be emptyDir. I'll create a pull request when I get off work.

Awesome - that's much appreciated!

> Side note: perhaps the location in the documents on could be moved its in a fairly obscure place for what is a fairly common customization.

I totally agree that the docs could use some significant reorganization.  If there's a location you feel would be better at this time, that would certainly be welcome.  We should try spend time on the docs at some point.

Thank you for pointing this out.  Any suggestions would also be appreciated.  We'd like to re-organize by "role" similar to how the [`jupyter_server` docs](https://jupyter-server.readthedocs.io/en/latest/?badge=latest#table-of-contents) are structured.

**Comment by ashvinnihalani** [comment]
https://zero-to-jupyterhub.readthedocs.io/en/latest/ does something similar. I really appreciated their docs and they all have the same design language.

**Comment by kevin-bates** [comment]
Created https://github.com/jupyter/enterprise_gateway/issues/881.
