### ISSUE TITLE
Can I use juputer_enterprise_gateway to improve resource utilization?

### ISSUE THREAD

**Issue by Jeffwan** [jupyter/enterprise_gateway#905]
Help us improve the Jupyter Enterprise Gateway project by reporting issues
or asking questions. 

## Description
My org would like to support notebook service to data scientist, current problem is we have limited GPU resource, if every notebook has one GPU, the challenge is we feel hard to recycle the resources (detecting user idle activity is kind of hard), GPU resource utilization end up low. 

I find this project might be helpful. Seems with this, we can use CPU notebook and connect to GPU kernels in our kubernetes cluster via EG.  However, there's some technical issues I am not very clear and I am trying to get community's help.

1. Does kernel support multiple GPUs? Could code runs on 2 GPUs a time? 
2. Is there's QoS guarantee? Let's say if user want to use 1GPU, is it possible to allocate entire GPU to that user? 
3. Is it a situation that multiple codes snippets run on one kernel backed by GPU? If so, what if one process use more GPU memory, the other one will be affected? How can we avoid this case? 
4. how does EG handle the dependencies? If the code has some third party dependencies? how does kernel pod fetch the dependencies and run it? 

## Screenshots / Logs
If applicable, add screenshots and/or logs to help explain your problem.
To generate better logs, please run the gateway with `--debug` command line parameter.

## Environment

- Enterprise Gateway Version [e.g. 1.x, 2.x, ...]
- Platform: [e.g. YARN, Kubernetes ...]
- Others [e.g. Jupyter Server 5.7, JupyterHub 1.0, etc]

**Comment by kevin-bates** [comment]
Hi @Jeffwan - thanks for the questions.

Separating the kernel from the notebook/desktop is exactly the benefit of EG.   Relative to k8s, EG manages kernel pod lifecycle and provides are fairly rich means by which per-kernel customizations can occur.  This is accomplished by providing a [jinja template for each kernel specification](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/kernel-kubernetes.html#kubernetes-kernel-instances) that is essentially the pod details.  So you can essentially configure the kernel pod however you like relative to what can be expressed in the k8s yaml (aka the kernel-pod.yaml file).  Where this particular aspect breaks down is when using Spark.  We currently don't support using the templates for the Spark on K8s kernels because it wasn't supported prior to 3.0.   PR #559 was developed using an early release, but we just haven't had the time to revisit.  That said, most of the interesting configuration items can be expressed via properties in the meantime.  This effort is slated in our EG 3.0 release.

Another area where customizations can occur is at the namespace level.  By default, EG creates an ephemeral namespace for each kernel pod to run within.  You can also bring your own namespace such that it can be pre-created and decorated with appropriate resource limits, etc.  You then convey that namespace in the kernel start request and your kernel pod will be placed into that namespace.

Again, EG doesn't assign specific kernels to specific GPUs or have the means to run portions of a notebook on different GPU.  These are things that need to be configured in the template and/or performed programmatically in the notebook code itself if you needed that kind of granularity.

Regarding dependencies, each kernel is associated with a [kernel image](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/docker.html#custom-kernel-images) which should house the appropriate dependencies needed for that kernel.  Other dependencies, like data sets, etc., would be made available to the kernel via [volume mounts](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/kernel-kubernetes.html#unconditional-volume-mounts).

I hope that helps with your questions.

**Comment by lafncow** [comment]
Can you please clarify how to provide the jinja template for a kernel? Does it go in the /usr/local/share/jupyter/kernels directory alongside the respective kernel.json?

**Comment by lafncow** [comment]
I think I found the answer, this makes it much clearer to me: https://github.com/jupyter/enterprise_gateway/blob/dc95b50d813430d5308d3f2457b020eb31d4b7bd/docs/source/docker.md

As I understand: edit the path to launch_kubernetes.py in your kernel.json so that it points to a custom launch_kubernetes.py and j2 template that can be in the same folder as the kernel.json.

**Comment by kevin-bates** [comment]
Hi @lafncow.  

Yes, you can replace _both_ `launch_kubernetes.py` (so long as the kernel.json's `argv` stanza is updated) **and** `kernel-pod.yaml.j2` as you say.  The intention, however, is to keep `launch_kubernetes.py` and only modify or replace `kernel-pod.yaml.j2`.  Replacement is then simply a matter of updating `launch_kubernetes.py`'s [`KERNEL_POD_TEMPLATE_PATH`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py#L12) value.

If you do decide to use a custom `launch_kubernetes.py` file it is imperative that you preserve the [keywords](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py#L34-L49) since many are _factory values_ needed by the target kernel.

I'm curious what portion of `launch_kubernetes.py` you need to customize since the intention is that only the j2 template be customized.  Can you share that?  (I'm just wondering if it might make sense to make that change part of the general offering.  Thanks.)

**Comment by lafncow** [comment]
Thank you for clarifying! As it turned out, no customization to `launch_kubernetes.py` was needed, I could make all the changes required in `kernel-pod.yaml.j2`.

**Comment by kevin-bates** [comment]
Awesome - glad to hear that.  

If you feel others might benefit from your changes and would like to share any steps you took that might not be obvious to others, this seems like it might make for a great documentation update, example or tip.

**Comment by gogasca** [comment]
Just as a comment, GKE supports [now](https://cloud.google.com/kubernetes-engine/docs/how-to/gpus-multi#create-cluster) A100 GPUs. To improve GPU utilization, multi-instance GPUs allow you to partition a single NVIDIA A100 GPU in up to seven slices. Each slice can be allocated to one container on the node independently, for a maximum of seven containers per one NVIDIA A100 GPU. This works fine with JEG.  You need to pass special KERNEL_ environment variables:

```
KERNEL_GPUS=1
KERNEL_GPUS_LIMIT=1
KERNEL_LAUNCH_TIMEOUT=90
```
