### ISSUE TITLE
Jupyterhub with nb2kg authentication problem

### ISSUE THREAD

**Issue by Tim1000V** [jupyter/enterprise_gateway#917]
## Description
Hi,
I have an issue with the nb2kg (v2.4.0), I'm actually spawning the nb2kg from a Jupyterhub server which also runs on kubernetes.
After some time (1~2 hours), there is authentification errors with the client, I guess it is due to a mismatch beetween the Jupyterhub version and the jupyter lahub version.
I tried with the latest version of jupyter but I believe it isn't compatible with the EG (HTTP response 200 on websocket request).
Is there any plan for supporting latest version of jupyter or I am missing something ?
At least can you tell me which relevant files I need to edit in order to resolve this issue for nb2kg 2.4.0 ?

## Logs
[W 2020-12-09 18:21:27.247 SingleUserLabApp auth:267] No Hub user identified for request
[W 2020-12-09 18:21:27.247 SingleUserLabApp auth:465] Token stored in cookie may have expired
[W 2020-12-09 18:21:27.248 SingleUserLabApp handlers:73] Couldn't authenticate WebSocket connection
[W 2020-12-09 18:21:27.251 SingleUserLabApp log:158] 403 GET /jupyterhub/user/username/api/kernels/59d85ce0-3e75-4731-b643-a9ed3783889b/channels?session_id=1b858888-288f-4bfd-9385-a203709964ae (@IP) 27.83ms
[I 2020-12-09 18:22:26.995 SingleUserLabApp log:158] 200 GET /jupyterhub/user/username/api/terminals?1607538123626 ([username@IP]username@IP) 1.12ms 

## Environment
- Enterprise Gateway Version 2.4.0
- Platform: Kubernetes
- Others: JupyterHub 1.2.1, Jupyter Labhub 0.9.2/Jupyter 4.4.0

**Comment by kevin-bates** [comment]
Hi @Tim1000V - I guess I have a few questions first.  

> I have an issue with the nb2kg (v2.4.0), 

[NB2KG](https://github.com/jupyter/nb2kg/releases) releases essentially stop at `0.7.0` and it's considered obsolete with Notebook versions > 6.0 (as its functionality is built into Notebook).  I suspect you mean Enterprise Gateway 2.4.0 (which does exist).

> I'm actually spawning the nb2kg from a Jupyterhub server which also runs on kubernetes.

Hmm.  If you mean EG instead of nb2kg, it, itself, is not spawned from JupyterHub.  JupyterHub spawns notebook servers and, when EG is desired, those notebook servers are then configured to _contact_ the EG server for their kernel management operations.

> After some time (1~2 hours), there is authentification errors with the client, I guess it is due to a mismatch beetween the Jupyterhub version and the jupyter lahub version.

I'm assuming you mean `jupyter lab`, which is just a different front-end on a Notebook server.  However, if your JupyterHub is spawning jupyter lab version 3.0 (which is still in a release-candidate phase), then the underlying server is `jupyter_server` not `notebook`.  However, either way, those are independent of Enterprise Gateway and EG can be used by either.  (EG itself if built on notebook server right now, FYI.)

> Is there any plan for supporting latest version of jupyter or I am missing something ?

Can you be more specific as to what the "latest version of jupyter" you're referring to?

The items in the log entries appear to be between Hub and the spawned Lab server and EG is not applicable there.  Are there log entries in the EG log that appear related?

Sounds like there's some kind of expiration happening.

**Comment by lresende** [comment]
@Tim1000V Could you try the 'elyra/elyra:1.5.2' image instead of nb2kg and if that gives you better results?

**Comment by kevin-bates** [comment]
Closing due to lack of reponse and stale versions.  We can re-open if that becomes necessary down the road.
