### ISSUE TITLE
Connection time out to the kernel pod 

### ISSUE THREAD

**Issue by JorisJamers** [jupyter/enterprise_gateway#932]
Hey All

## Description

We implemented the Enterprise Gateway on a second cluster in our environment. On the second cluster tho, we get a ContainerCreating state and it will throw us an error in the end that the EGW couldn't connect to the running pod (No healthy state return) 

I tried to play with the following environment variables, but they did not seem to work: 

```
 - name: EG_KERNEL_LAUNCH_TIMEOUT
      value: "600"
  - name: EG_JUPYTER_GATEWAY_CONNECT_TIMEOUT
      value: "600"
```

Are there any other variables that could extend the waiting time for the pod? If I check the kubernetes logs there is not really an issue with the scheduling or creation of the pod, no missing pvcs / resources / ... 

I can also provide more specific kubernetes logs if necessary. 

## Screenshots / Logs

```
[D 2021-02-09 10:29:43.904 EnterpriseGatewayApp] 76: Waiting to connect to k8s pod in namespace <namespace>. Name: 'guest-143b70c7-9d60-4ca1-9ba7-61c2cf585646', Status: 'Pending', Pod IP: 'None', KernelID: '143b70c7-9d60-4ca1-9ba7-61c2cf585646'
[W 2021-02-09 10:29:44.427 EnterpriseGatewayApp] Unable to delete pod: {'api_version': 'v1',
     'code': None,
     'details': None,
     'kind': 'Pod',
     'message': None,
     'metadata': {'_continue': None,
                  'remaining_item_count': None,
                  'resource_version': '13186477',
                  'self_link': '/api/v1/namespaces/pods/guest-143b70c7-9d60-4ca1-9ba7-61c2cf585646'},
     'reason': None,
     'status': "{'phase': 'Pending', 'conditions': [{'type': 'Initialized', "
               "'status': 'True', 'lastProbeTime': None, 'lastTransitionTime': "
               "'2021-02-09T10:29:08Z'}, {'type': 'Ready', 'status': 'False', "
               "'lastProbeTime': None, 'lastTransitionTime': "
               "'2021-02-09T10:29:08Z', 'reason': 'ContainersNotReady', 'message': "
               "'containers with unready status: "
               "[guest-143b70c7-9d60-4ca1-9ba7-61c2cf585646]'}, {'type': "
               "'ContainersReady', 'status': 'False', 'lastProbeTime': None, "
               "'lastTransitionTime': '2021-02-09T10:29:08Z', 'reason': "
               "'ContainersNotReady', 'message': 'containers with unready status: "
               "[guest-143b70c7-9d60-4ca1-9ba7-61c2cf585646]'}, {'type': "
               "'PodScheduled', 'status': 'True', 'lastProbeTime': None, "
               "'lastTransitionTime': '2021-02-09T10:29:08Z'}], 'hostIP': "
               "'10.56.100.11', 'startTime': '2021-02-09T10:29:08Z', "
               "'containerStatuses': [{'name': "
               "'guest-143b70c7-9d60-4ca1-9ba7-61c2cf585646', 'state': {'waiting': "
               "{'reason': 'ContainerCreating'}}, 'lastState': {}, 'ready': False, "
               "'restartCount': 0, 'image': "
               "'image', "
               "'imageID': '', 'started': False}], 'qosClass': 'Burstable'}"}
[W 2021-02-09 10:29:44.427 EnterpriseGatewayApp] KubernetesProcessProxy.terminate_container_resources, pod: guest-143b70c7-9d60-4ca1-9ba7-61c2cf585646, kernel ID: 143b70c7-9d60-4ca1-9ba7-61c2cf585646 has not been terminated.
[E 2021-02-09 10:29:44.427 EnterpriseGatewayApp] KernelID: '143b70c7-9d60-4ca1-9ba7-61c2cf585646' launch timeout due to: Waited too long (40.0s) to get connection file
```

## Environment

- Kubernetes 1.18 (on prem) 

Kind regards 
Joris

**Comment by kevin-bates** [comment]
Hi Joris.  

`KERNEL_LAUNCH_TIMEOUT` is essentially a client-provided value and tightly coupled with `JUPYTER_GATEWAY_REQUEST_TIMEOUT` if you're using the `--gateway-url` option on your notebook invocations.  Are you increasing either of these values in your client configurations?  The notebook/jupyter-server code will essentially [honor the larger of these values and set the other accordingly](https://github.com/jupyter/notebook/blob/master/notebook/gateway/managers.py#L267-L274) - such that the request timeout is a couple of seconds longer than the launch timeout.  The log is showing the default of `40` seconds still in use.

Also, I would recommend seeding your nodes with the desire images.  This is the purpose of the Kernel Image Puller (KIP) daemonset, although that's not always viable for folks in certain environments.    At any rate, if your timeout is due to the initial image pulls, you might try seeding your nodes with appropriate images.

**Comment by JorisJamers** [comment]
> Hi Joris.
> 
> `KERNEL_LAUNCH_TIMEOUT` is essentially a client-provided value and tightly coupled with `JUPYTER_GATEWAY_REQUEST_TIMEOUT` if you're using the `--gateway-url` option on your notebook invocations. Are you increasing either of these values in your client configurations? The notebook/jupyter-server code will essentially [honor the larger of these values and set the other accordingly](https://github.com/jupyter/notebook/blob/master/notebook/gateway/managers.py#L267-L274) - such that the request timeout is a couple of seconds longer than the launch timeout. The log is showing the default of `40` seconds still in use.
> 
> Also, I would recommend seeding your nodes with the desire images. This is the purpose of the Kernel Image Puller (KIP) daemonset, although that's not always viable for folks in certain environments. At any rate, if your timeout is due to the initial image pulls, you might try seeding your nodes with appropriate images.

Hi @kevin-bates 

Thanks for the answer! The seeding of the images is something I already did, because I was aware that this could take a while. :D I'm using the following command to spin up my notebook server 
`jupyter notebook --gateway-url=http://foo.bar --GatewayClient.http_user=guest --GatewayClient.http_pwd=guest-password`
Is the `JUPYTER_GATEWAY_REQUEST_TIMEOUT` something I can pass along with this command? Or can I put it in the yaml file for the EGW? 

Thanks!

**Comment by kevin-bates** [comment]
`JUPYTER_GATEWAY_REQUEST_TIMEOUT` must be set on the client and has no relevance to EG since it's "active" between the client and EG.  It too can be set via the `--GatewayClient.request_timeout`.

Note that you can get a dump of all configurable options by running `jupyter notebook --help-all`.  FWIW, here's the output relative to `request_timeout`:
```
--GatewayClient.request_timeout=<Float>
    Default: 40.0
    The time allowed for HTTP request completion.
    (JUPYTER_GATEWAY_REQUEST_TIMEOUT env var)
```

`KERNEL_LAUNCH_TIMEOUT` is only available via env, but if you set `request_timeout` it will be set to the same value.  (Looks like I got rid of the 2-second pad between the two values at some point.)

**Comment by JorisJamers** [comment]
Hey Kevin 

I tried to use the following in the notebook command. I added the --GatewayClient.request_timeout=x . 

```
jupyter notebook --gateway-url=http://foo.bar --GatewayClient.http_user=guest --GatewayClient.http_pwd=guest-password --GatewayClient.request_timeout=602
```

And this is what I'm using in my deployment of EGW. 

```
- name: EG_KERNEL_LAUNCH_TIMEOUT
  value: "600"
- name: EG_JUPYTER_GATEWAY_CONNECT_TIMEOUT
  value: "600"
```

Unfortunately I still get the 40sec timeout. Are there other things to try?

**Comment by kevin-bates** [comment]
Hi Joris - neither of these properties apply to EG's instance so the EGW deployment changes are not necessary.

Please provide the debug output of the EG pod's log that includes the complete kernel start request output.

Also, what version of Notebook are you running and is the notebook server running in a Jupyter Hub environment?

I would also recommend enabled debug tracing on your notebook server (`--debug`) and provide its output also during the kernel startup attempt.

Since each of the `GatewayClient` parameters can be mapped to env variables (per the output of `--help-all`) that might also be something to try in case there's an issue with the handling of the CLI options.  So you know if your user `'guest'` is getting conveyed as `KERNEL_USERNAME` on the EG side within your request.  (This should be visible in the EG console output as well.)

Thanks.

**Comment by JorisJamers** [comment]
Hi Kevin 

These are the versions of jupyter I am running : 

```
jupyter core     : 4.6.1
jupyter-notebook : 6.0.2
qtconsole        : 4.6.0
ipython          : 7.10.2
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 1.2.4
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3
```

And these are the full logs of the kernel start request: 

```
BaseProcessProxy.launch_process() env: {'SHELL': '/bin/bash', 'KUBERNETES_SERVICE_PORT_HTTPS': '443', 'EG_MIRROR_WORKING_DIRS': 'False', 'EG_JUPYTER_GATEWAY_CONNECT_TIMEOUT': '600', 
'KUBERNETES_SERVICE_PORT': '443', 'EG_NAMESPACE': 'testns', 'ENTERPRISE_GATEWAY_SERVICE_PORT_HTTP': '8888', 'TENSOR_SERVICE_PORT_80_TCP_PORT': '80', 
'HOSTNAME': 'enterprise-gateway-5c77f9b6cb-lstfv', 'LANGUAGE': 'en_US.UTF-8', 'EG_SHARED_NAMESPACE': 'True', 'EG_PORT': '8888', 'EG_LOG_LEVEL': 'DEBUG', 
'JAVA_HOME': '/usr/lib/jvm/java-8-openjdk-amd64', 'EG_KERNEL_WHITELIST': "['pytorchplus/kernel:active']", 'NB_UID': '1000', 
'ENTERPRISE_GATEWAY_SERVICE_HOST': '172.16.37.170', 'PWD': '/usr/local/bin', 'EG_CULL_IDLE_TIMEOUT': '43200', 'EG_DEFAULT_KERNEL_NAME': 'python_docker', 
'TENSOR_SERVICE_PORT': 'tcp://172.16.3.156:80', 'ENTERPRISE_GATEWAY_PORT_8888_TCP_PORT': '8888', 'MINICONDA_MD5': '87e77f097f6ebb5127c77662dfc3165e', 'EG_ENABLE_TUNNELING': 'False', 
'ENTERPRISE_GATEWAY_PORT_8888_TCP_ADDR': '172.16.37.170', 'EG_KERNEL_LAUNCH_TIMEOUT': '600', 'HOME': '/home/jovyan', 'LANG': 'en_US.UTF-8', 
'KUBERNETES_PORT_443_TCP': 'tcp://172.16.0.1:443', 'EG_LIST_KERNELS': 'True', 'EG_SSH_PORT': '2122', 'NB_GID': '100', 'TENSOR_SERVICE_SERVICE_HOST': '172.16.3.156', 
'ENTERPRISE_GATEWAY_PORT_8888_TCP': 'tcp://172.16.37.170:8888', 'TENSOR_SERVICE_PORT_80_TCP_PROTO': 'tcp', 'EG_KERNEL_SESSION_PERSISTENCE': 'False', 'KG_PORT': '8888', 
'EG_CULL_CONNECTED': 'False', 'EG_PORT_RETRIES': '0', 'KG_IP': '0.0.0.0', 'TENSOR_SERVICE_SERVICE_PORT': '80', 'EG_CULL_INTERVAL': '60', 'EG_IP': '0.0.0.0', 
'SHLVL': '0', 'CONDA_DIR': '/opt/conda', 'MINICONDA_VERSION': '4.8.2', 'ENTERPRISE_GATEWAY_SERVICE_PORT': '8888', 'SPARK_HOME': '/opt/spark', 
'KUBERNETES_PORT_443_TCP_PROTO': 'tcp', 'KG_PORT_RETRIES': '0', 'TENSOR_SERVICE_PORT_80_TCP_ADDR': '172.16.3.156', 'TENSOR_SERVICE_PORT_80_TCP': 'tcp://172.16.3.156:80', 
'KUBERNETES_PORT_443_TCP_ADDR': '172.16.0.1', 'SPARK_VER': '2.4.6', 'ENTERPRISE_GATEWAY_PORT': 'tcp://172.16.37.170:8888', 'CONDA_VERSION': '4.8.2', 'NB_USER': 'jovyan', 
'KUBERNETES_SERVICE_HOST': '172.16.0.1', 'ENTERPRISE_GATEWAY_PORT_8888_TCP_PROTO': 'tcp', 'LC_ALL': 'en_US.UTF-8', 'KUBERNETES_PORT': 'tcp://172.16.0.1:443', 
'KUBERNETES_PORT_443_TCP_PORT': '443', 'PATH': '/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'EG_KERNEL_CLUSTER_ROLE': 'kernel-controller', 
'DEBIAN_FRONTEND': 'noninteractive', 'KERNEL_LAUNCH_TIMEOUT': '40', 'KERNEL_USERNAME': 'guest', 'KERNEL_GATEWAY': '1', 'KERNEL_POD_NAME': 'guest-21e2da41-bb09-4904-b80c-01b5c98a4f90', 
'KERNEL_SERVICE_ACCOUNT_NAME': 'default', 'KERNEL_NAMESPACE': 'testns', 'KERNEL_IMAGE': 'pytorchplus/kernel:active', 
'KERNEL_EXECUTOR_IMAGE': 'pytorchplus/kernel:active', 'KERNEL_UID': '1000', 'KERNEL_GID': '100', 'EG_MIN_PORT_RANGE_SIZE': '1000', 
'EG_MAX_PORT_RANGE_RETRIES': '5', 'KERNEL_ID': '21e2da41-bb09-4904-b80c-01b5c98a4f90', 'KERNEL_LANGUAGE': 'python', 'EG_IMPERSONATION_ENABLED': 'False'}
[I 2021-02-15 07:23:24.728 EnterpriseGatewayApp] KubernetesProcessProxy: kernel launched. Kernel image: pytorchplus/kernel:active, KernelID: 21e2da41-bb09-4904-b80c-01b5c98a4f90, cmd: '['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/pytorch_plus_1/scripts/launch_kubernetes.py', '--RemoteProcessProxy.kernel-id', '21e2da41-bb09-4904-b80c-01b5c98a4f90', '--RemoteProcessProxy.response-address', '172.16.120.119:8877']'
[D 2021-02-15 07:23:25.425 EnterpriseGatewayApp] 1: Waiting to connect to k8s pod in namespace 'testns'. Name: '', Status: 'None', Pod IP: 'None', KernelID: '21e2da41-bb09-4904-b80c-01b5c98a4f90'
[D 2021-02-15 07:24:04.511 EnterpriseGatewayApp] 74: Waiting to connect to k8s pod in namespace 'testns'. Name: 'guest-21e2da41-bb09-4904-b80c-01b5c98a4f90', Status: 'Pending', Pod IP: 'None', KernelID: '21e2da41-bb09-4904-b80c-01b5c98a4f90'
[W 2021-02-15 07:24:05.033 EnterpriseGatewayApp] Unable to delete pod: {'api_version': 'v1',
     'code': None,
     'details': None,
     'kind': 'Pod',
     'message': None,
     'metadata': {'_continue': None,
                  'remaining_item_count': None,
                  'resource_version': '16592866',
                  'self_link': '/api/v1/namespaces/testns/pods/guest-21e2da41-bb09-4904-b80c-01b5c98a4f90'},
     'reason': None,
     'status': "{'phase': 'Pending', 'conditions': [{'type': 'Initialized', "
               "'status': 'True', 'lastProbeTime': None, 'lastTransitionTime': "
               "'2021-02-15T07:23:30Z'}, {'type': 'Ready', 'status': 'False', "
               "'lastProbeTime': None, 'lastTransitionTime': "
               "'2021-02-15T07:23:30Z', 'reason': 'ContainersNotReady', 'message': "
               "'containers with unready status: "
               "[guest-21e2da41-bb09-4904-b80c-01b5c98a4f90]'}, {'type': "
               "'ContainersReady', 'status': 'False', 'lastProbeTime': None, "
               "'lastTransitionTime': '2021-02-15T07:23:30Z', 'reason': "
               "'ContainersNotReady', 'message': 'containers with unready status: "
               "[guest-21e2da41-bb09-4904-b80c-01b5c98a4f90]'}, {'type': "
               "'PodScheduled', 'status': 'True', 'lastProbeTime': None, "
               "'lastTransitionTime': '2021-02-15T07:23:30Z'}], 'hostIP': "
               "'10.56.100.10', 'startTime': '2021-02-15T07:23:30Z', "
               "'containerStatuses': [{'name': "
               "'guest-21e2da41-bb09-4904-b80c-01b5c98a4f90', 'state': {'waiting': "
               "{'reason': 'ContainerCreating'}}, 'lastState': {}, 'ready': False, "
               "'restartCount': 0, 'image': "
               "'pytorchplus/kernel:active', "
               "'imageID': '', 'started': False}], 'qosClass': 'Burstable'}"}
[W 2021-02-15 07:24:05.033 EnterpriseGatewayApp] KubernetesProcessProxy.terminate_container_resources, pod: testns.guest-21e2da41-bb09-4904-b80c-01b5c98a4f90, kernel ID: 21e2da41-bb09-4904-b80c-01b5c98a4f90 has not been terminated.
[E 2021-02-15 07:24:05.033 EnterpriseGatewayApp] KernelID: '21e2da41-bb09-4904-b80c-01b5c98a4f90' launch timeout due to: Waited too long (40.0s) to get connection file
[E 210215 07:24:05 web:2250] 500 POST /api/kernels (172.16.120.6) 40356.58ms
```

I start the notebook in a anaconda3 CLI, I'm not using lab right now.. Hopefully this will give you more insight about what's going wrong. We are using the same setup on our initial kubernetes cluster and we don't have this issue on that cluster. The only difference is that this new cluster is multi-node and the first that we use is single-node. 

Thanks! 
Joris

**Comment by kevin-bates** [comment]
Hi Joris,

So, there are a couple of issues here:
1. `KERNEL_LAUNCH_TIMEOUT` is not reflecting the CLI configuration setting: `--GatewayClient.request_timeout=602`
2. Your kernels are taking longer than 40 seconds to start despite the nodes being pre-seeded with their images. That shouldn't be the case and implies there could be something in play here that an increased timeout won't resolve.

Regarding the value of KLT, you're running Notebook `6.0.2`, which is over two years old.  This release only ensures that the request-timeout is at least the value of KLT, but doesn't have the reciprocating logic to ensure KLT is at least request_timeout.  As a result, you will need to set KLT directly, which means it needs to come from the environment.  The other option would be to upgrade to `6.1.x` when both values are synchronized to the higher value.

Regarding the start timeout even when the nodes have the images, you should try to access the container logs during their 40 seconds attempting to start.  I also try to gather information using `kubectl describe` - it might show some unexpected issues as well.  Since you're using your own namespace (`testns`) and all kernels are also in that namespace, at least you can just monitor that namespace for when the kernel pod pops up.

That said, if the container isn't starting, which appears to be the case based on the failure to delete the pod, accessing the logs may not be an option - and using `kubectl describe` may be all you have.

I would still focus on increasing the timeout, but if you find timeouts still occurring after 10 minutes KLTs, you'll need to dig into why.  Multiple nodes should not make a difference.  The image just isn't getting off the ground.

**Comment by JorisJamers** [comment]
Hey @kevin-bates  

First of all thank you for the great help in this issue! I just found my problem. It had nothing to do with EGW or Jupyter. Describing the pod is something I did way before I reached out in this issue page. :) But it didn't really gave me output, so I had no idea what was happing in the pod. 

Now.. With the use of  `kubectl get events -n testns` I did get some useable output. Didn't really came up in my mind to use the get events command. 

But It was indeed a underlying kubernetes issue. We copied persistentvolumes & persistentvolumeclaims from our first cluster. Since we are using NFS the pv & pvc didn't really complain whilst creating the resources. Although there is probably some kind of connection issue to the NFS server in our first cluster. I changed the pv & pvc accordingly to several other namespaces we are using on the second cluster and it works fine now! 

```
[user@node]$ k get pods -n testns
enterprise-gateway-5c77f9b6cb-lstfv          1/1     Running   0          7d2h
guest-3f7da7ee-6b2e-4d50-8abb-490c9268ab02   1/1     Running   0          6s
kernel-image-puller-4xswp                    1/1     Running   0          12d
kernel-image-puller-jv5rc                    1/1     Running   0          12d
kernel-image-puller-klxrw                    1/1     Running   0          12d
kernel-image-puller-kxqzv                    1/1     Running   0          12d
kernel-image-puller-rzn42                    1/1     Running   0          12d
kernel-image-puller-zwnbw                    1/1     Running   0          12d
```

Thanks again for putting me in the right direction!  I'll close this issue. 

Kind regards 
Joris

**Comment by kevin-bates** [comment]
Thanks for the update @JorisJamers - I'm glad to hear you're moving forward.

Were you able to get `KERNEL_LAUNCH_TIMEOUT` to flow by setting it directly or upgrading your notebook version?  It would be helpful to know that aspect of things got resolved as well.  Thanks.
