### ISSUE TITLE
`--EnterpriseGatewayApp.port_range` option isn't propagated to kubernetes kernel pods

### ISSUE THREAD

**Issue by telamonian** [jupyter/enterprise_gateway#934]
## Description

When using jeg in a k8s environment, the `--EnterpriseGatewayApp.port_range` is respected by the gateway pods (in terms of the ports specified in the return address passed down into the kernel pods), but is ignored by the kernel pods. This seems to be due to the fact that there is no mechanism currently by with `port_range` can get passed down into kernel pods. This is in spite of the fact that `launch_ipykernel.py` can take a `--RemoteProcessProxy.port-range` arg:

https://github.com/jupyter/enterprise_gateway/blob/89a822ce815519b486caba420603a70fe4a40c67/etc/kernel-launchers/python/scripts/launch_ipykernel.py#L369-L370

Let me know if I'm missing something here. Otherwise I'll get to work on a PR to fix this.

## Environment

- Enterprise Gateway Version 2.3
- Platform: kube
- Others: jlab 2.2.8

**Comment by kevin-bates** [comment]
Hi Max, you're absolutely correct - thank you for pointing this out, and sorry for the inconvenience.

Yeah, this will need to be plumbed through [`launch_kubernetes.py`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py)/[`kernel-pod.yaml.j2`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml.j2) to [`bootstrap_kernel.sh`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernel-launchers/bootstrap/bootstrap-kernel.sh) in order to set the options for the various kernel launchers.

I think using an env would be great.  In fact, since all `KERNEL_` envs flow automatically, you _could_ use `KERNEL_PORT_RANGE` (and perhaps default it from `EG_PORT_RANGE`), then you'd only need to update `bootstrap_kernel.sh` to repurpose the env as the CLI option. That said, having support for the CLI option in `launch_kubernetes.py` would be consistent.

**Comment by telamonian** [comment]
PR is incoming
