### ISSUE TITLE
Can we have a terminal for the kernel pods.

### ISSUE THREAD

**Issue by abinassahoo** [jupyter/enterprise_gateway#967]
## Description
Hi Team,
Currently we are using Jupyter Enterprise gateway for various python kernels . However sometime finds it difficult to manage all python package installation inside the kernel pod notebook. 

It would be really great if you can help me understand whether we can enable some terminal for the kernel pods where it will be easy for managing all shell/linux related commands.
 

## Environment

- Enterprise Gateway Version : 2.4
- Platform: Kubernetes

**Comment by kevin-bates** [comment]
I'm not sure I understand the request.  Are you asking that a terminal _application_ be developed that can "connect" to a running kernel pod to provide a user access to the pod's shell in order to install packages, etc.?

While Notebook/Lab expose a terminal application, it only runs on the corresponding notebook server - which just so happens to be where the kernel is running.  However, kernel pods are ephemeral, so, even if such an application existed, you'd still need to repeat those same operations on each kernel lifecycle.

You should be able to install ad-hoc packages via a Python kernel using `!pip install <package>` from the notebook and would likely be better off just amending some cells in the Notebook itself that "setup" the correct environment.

Of course, the best approach would be to add the foreseen packages to the [kernel image itself](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/docker.html#extending-existing-kernel-images) - which will survive kernel restarts, etc.

We don't have plans to support a terminal application targeting the kernel's (remote) location.

Not sure if this would be helpful, but Jupyter Lab offers "consoles" which are shell-like facades over a kernel.  Lab also offers the ability to change a kernel to use a current kernel session. So one could conceivably start a kernel.  Then start a console, but change the console's kernel to that of the original kernel.  Now you've got a kernel and a console associated with the same kernel.  Commands like `ls` and `pip` do not require the `'!'` prefix from the console and you're not having to enter the "commands" within a cell by using the console.

**Comment by abinassahoo** [comment]
Thank you @kevin-bates for the response. Apologies for delayed reply. 
Yes, currently I am using our own image as described [here](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/docker.html#bringing-your-own-kernel-image), where the startup command for the image is set as `/usr/local/bin/bootstrap-kernel.sh` . 

So are you suggesting to start jupyter lab command as well while starting the kernel pod.
> Not sure if this would be helpful, but Jupyter Lab offers "consoles" which are shell-like facades over a kernel. Lab also offers the ability to change a kernel to use a current kernel session. So one could conceivably start a kernel. Then start a console, but change the console's kernel to that of the original kernel. Now you've got a kernel and a console associated with the same kernel. Commands like `ls` and `pip` do not require the `'!'` prefix from the console and you're not having to enter the "commands" within a cell by using the console.

**Comment by abinassahoo** [comment]
Hi @kevin-bates ,
I tired the same by starting the lab and from there tried to launch one of the kernel console mapped to EG, still it seems it only accepts similar input as notebook. Means we have to use ! before any shell command.

![image](https://user-images.githubusercontent.com/18737307/117982134-54206a00-b353-11eb-861f-e02c81e6e0b7.png)

**Comment by kevin-bates** [comment]
Interesting.  It looks like there must be a filter on what commands are permitted and `pip` isn't one of them (so `!pip` is required)...
![image](https://user-images.githubusercontent.com/22599560/118001101-44753700-b2fb-11eb-8ad3-1f938d10d9c4.png)

This must be a restriction imposed by the console implementation since I can enter `pip list` directly in `IPython`.

**Comment by abinassahoo** [comment]
Yeah, It seems still some of the command is working without ! as well. Thank you so much @kevin-bates . It really helped. This can be marked as closed.

**Comment by kevin-bates** [comment]
Cool - glad you're moving forward!
