### ISSUE TITLE
Strange behavior of Jupyter with sys.path

### ISSUE THREAD

**Issue by faurik** [jupyter/enterprise_gateway#985]
Hello!

We have following setup:
1. JupyterHub (v1.1.0) running on Kubernetes cluster
2. Jupyter Notebook Servers are running as pods on the same cluster
3. Jupyter Enterprise Gateway (v2.4.0) running on Cloudera edge nodes
4. Cloudera cluster with HDFS, YARN, Spark.

We are trying to use Jupyter Enterprise Gateway to make it possible to run kernels on Spark cluster from Jupyter Notebooks on Kubernetes. The problem is that we cannot use it properly with virtual environments.

Users are creating virtual envs using following approach:
```
conda create -n VIRTUAL_ENV_NAME
conda install --file requirements.txt
(cd ~/.conda/envs/VIRTUAL_ENV_NAME/lib/python*/site-packages && zip -r - *) > dependencies.zip
cp dependencies.zip /some/shared/folder/across/whole/cluster
```

And after that users are using this in their Spark code:
```
config = SparkConf.setAll([
  ('spark.yarn.dist.archives', '/some/shared/folder/across/whole/cluster/DESIRED/PATH/dependencies.zip#deps'),
  ('spark.yarn.appMasterEnv.PYTHONPATH', 'deps:' + sc.getConf().get('spark.yarn.appMasterEnv.PYTHONPATH')),
  ('spark.executorEnv.PYTHONPATH', 'deps:' + sc.getConf().get('spark.executorEnv.PYTHONPATH')),
  ... other configuration options for Spark ...
])

sys.path.append("/some/shared/folder/across/whole/cluster/dependencies.zip")

sc.stop()
sc = SparkContext(conf=config)
```

The problem is quite weird and relates to `sys.path`: if some package exists in both Python library and virtual environment, then package from Python library takes precedence. 

Expected behavior (it worked with raw Python):
![image](https://user-images.githubusercontent.com/25117696/127312960-dda50bcc-ebb3-4e45-8e95-865d87484258.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/25117696/127313268-3b9e4601-7202-4614-b1df-2ab203a2fee3.png)

But if some package is absent in Python library location, it will be loaded from our virtualenv (path in `sys.path.insert()`), so it really looks like some issue with priority of items in `sys.path`. 

I am not sure what the problem related with: maybe it relates to ipykernel, or[ launch script](https://github.com/jupyter/enterprise_gateway/blob/v2.4.0/etc/kernel-launchers/python/scripts/launch_ipykernel.py).

Please let me know if some additional information is required.

**Comment by kevin-bates** [comment]
Hmm - this is an interesting configuration, but it can be simplified to just EG on a YARN edge node launch kernels in the YARN cluster.  That is, you could hit the EG server from a non-Hub notebook server and experience the same issue.

Have you checked that your `bin/run.sh` (in the kernelspec directory) isn't introducing any issues since it sets up env variables, etc.?
I suppose this could be related to the namespace stuff the `launch_ipykernel.py` is doing, but I'd be surprised this kind of thing hasn't come up before.

Honestly, this might be a bit outside my wheel-house so perhaps someone else can chime in or you just have to keep digging - sorry.

**Comment by kevin-bates** [comment]
Closing due to lack of response.  We can re-visit/re-open if things change.
