### ISSUE TITLE
kernel image puller support k8s cluster with containerd instead of docker

### ISSUE THREAD

**Issue by abzymeinsjtu** [jupyter/enterprise_gateway#992]
## Description

k8s is now removing docker support and replace it with containerd as default container engine. In EG, the kernel_image_puller script doesn't seem to support k8s cluster with containerd. 

so some improvement may be applied to current script and eg yaml file.

## Screenshots / Logs

![截屏2021-08-13 下午4 05 17](https://user-images.githubusercontent.com/4393648/129325179-9e736fbd-498e-4dae-9f73-ab6cdd69d450.png)

![截屏2021-08-13 下午4 05 59](https://user-images.githubusercontent.com/4393648/129325246-df3d742c-fb54-46a8-b56b-5483f34da658.png)

![截屏2021-08-13 下午8 46 17](https://user-images.githubusercontent.com/4393648/129359158-1487828a-6e88-4a9d-a546-086f7d385ba7.png)

## Environment

- Enterprise Gateway Version 2.5
- Platform: Kubernetes

**Comment by kevin-bates** [comment]
Sigh.  Not sure what to do other than not deploy KIP and go back to having initial kernel invocations timeout due to their image upload.  

Is it possible to detect the container runtime (or convey it via helm values [which is certainly possible]) and update KIP to use the right mechanism?  I don't know anything about `containerd` at the moment (and don't have time to learn new stuff).  At a minimum, we could convey via an environment variable and only have KIP active if Docker is conveyed - just to prevent crash loops. 

I'm sorry about this.  Ideas and contributions are more than welcome!

**Comment by abzymeinsjtu** [comment]
> Is it possible to detect the container runtime (or convey it via helm values [which is certainly possible]) and update KIP to use the right mechanism? I don't know anything about `containerd` at the moment (and don't have time to learn new stuff). At a minimum, we could convey via an environment variable and only have KIP active if Docker is conveyed - just to prevent crash loops.
> 

yes, V1Node object contains information about container runtime [object](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1NodeSystemInfo.md), such as docker://{version}, containerd://{version}.


and there is also python [containerd](https://pypi.org/project/containerd/) lib

**Comment by abzymeinsjtu** [comment]
@kevin-bates 

if so, i will be working on this later

**Comment by abzymeinsjtu** [comment]
seems that containerd gRPC has no method to pull image, i can just failover when running without docker engine now

**Comment by kevin-bates** [comment]
Addressed in #995
